### ISSUE TITLE
Features of EDIT WEB ENTITY page

### ISSUE THREAD

**Issue by jacomyma** [medialab/hyphe#108]
This page gives information at the web entity level.

As a starting point, we list required questions and actions. There is a lot of overlap and the order is not representative of possible user interfaces, we deal with this later.
## Unordered list of requisites

Topics and things users search for:
- IDENTITY: who is this web entity? (tags, properties, profile...)
- LINKS: who links this entity and who it links?
- CONTENT: which pages do we know? How are they linked? (structure)
- MEASURES: most linked pages from outside, rankings such as centrality...
- PREVIEW: previewing pages? At least some links.

Features:
- split / merge web entities
- edit properties (title, home page...)
- edit tags
## Proposition for a UI structure
1. **Summary**: Generic data giving a general idea of the web entity. Details are provided in other views. Measures take place here (indegree, outdegree, centrality, clustering coefficient...)
2. **Explorer**: Browse the content as classic folders and redefine web entities. Contains prefixes and not only pages.
3. **Pages Network**: A split screen of a network and a list of pages, where pages are sortable by different measures (indegree, outdegree, depth...) and the network visualization has two modes: force vector and depth tree. In the network, pages could be colored according to uncrawled/crawlDepth. (also add an option to include links to external pages/webentities?)
4. **Ego Network**: The ego network of the web entity. Should provide insights on the distribution of tags, as well as other measures such as indegree...
5. **Tags**: to define when we work on tags
6. **Advanced settings**: other rarely used or potentially dangerous settings, such as manually adding or removing a prefix.

**Comment by boogheta** [comment]
Adding or removing a prefix can be a quite common need, I'd rather see it in the summary ad previously than in advanced settings

**Comment by paulgirard** [comment]
The term Explorer is not very clear to me .
explore web entity LRU tree ? Let's see what Mathieu already did

**Comment by boogheta** [comment]
We probably need also a tab displaying the list of all crawl jobs related to the webentity

**Comment by boogheta** [comment]
We also need a button to CRAWL the current webentity from here, this probably don't needs to be a dedicated tab, but maybe just a link to the CRAWL pages

**Comment by boogheta** [comment]
closing this as most of its features are already there or detailed in dedicated issues
