### ISSUE TITLE
New server with Hyphe

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#110]
Hi Medialab,

Both Anders Munk and I are planing to use Hyphe in the teaching of two upcoming courses this spring. Discovering the amount of work you have put into the project recently we decided that we want to setup a new version of Hyphe. However I'm unsure when will be a good time to pull a stabel and working version? - or if we by chance could we be so lucky that you had a new release in the pipeline?

Best regards
Tobias Bornakke

**Comment by boogheta** [comment]
Hi Tobias, and yes!
We plan to release a stable version by the end of february. Still a few important features are in the pipe, until then, I'd recommand you wait a little bit more. Thanks!

**Comment by boogheta** [comment]
guess we can close this one now?
Althoughn you should git pull and bin/hyphe restart : I fixed the two issues we discovered while installing.

**Comment by bornakke** [comment]
Yes - and thank you :)
