### ISSUE TITLE
Failing to create Alias on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by intensifier** [medialab/hyphe#111]
Hello, 

First of all: Hyphe is a fantastic software. It really takes my social scientific research to a new level! Thanks for sharing it!

I have installed Hyphe successfully on a number of Debian 7 machines. Now I am trying to install it on a Ubuntu 14.04.2 LTS machine. Everything works smoothly with the install script (except one has to manually add the GPG keys for the scrapy repository). But during the final step of getting the web frontend to work, I run into trouble. When trying to access the **/hyphe directory**, I get a **404 Not Found**

This is my hyphe_www_client/_config/apache2.conf:

    <VirtualHost *:80>
    Alias /hyphe /home/anon/Hyphe/hyphe_www_client
	ServerName 130.241.40.130
    <Directory /home/anon/Hyphe/hyphe_www_client>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
    </Directory>
    </virtualHost>

And this is my hyphe_www_client/_config/config.js

    HYPHE_CONFIG = {
	"SERVER_ADDRESS":"http://130.241.40.130:6978",
	"JAVASCRIPT_LOG_VERBOSE":false
    }

My Debian and Ubuntu installs look quite identical. However, I am sustpecting there is a difference in how the two distributions handle and configure Apache with regards to the Alias function. 

Has anyone had similar experiences?

**Comment by bornakke** [comment]
I installed it on ubuntu 14.04.02 last week without any problems.

Are you able to access other folders in your home directory?

**Comment by intensifier** [comment]
@bornakke Unfortunately not. I created the following test site: 

    <VirtualHost *:80>
    Alias /test /home/anon/test
	ServerName 130.241.40.130
    <Directory /home/anon/test>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
    </Directory>
    </virtualHost>

The /home/anon/test directory is chowned to www-data. Still I get the same 404 error when trying to access localhost/test. I must be doing something very wrong with apache (not hyphe).

**Comment by bornakke** [comment]
I'm not a specialist with apache, but shouldn't your servername be localhost if that is how you are trying to install it? Or are you trying to install it on a server in which case you should try to access it through 130.241.40.130/hyphe/

**Comment by intensifier** [comment]
@bornakke Thanks for that comment. I tried a different approach, which is sort of an ugly hack. 

1. I disabled the default config with **a2dissite 000-default.conf**. 
2. Then I changed the default config in /etc/apache2/apache2.conf to lead to my /home/anon/Hyphe/hyphe_www_client directory (which is chowned for the home user as it should, otherwise the memory access for java breaks). 
3. With a reboot of Apache, it now works, both from localhost and over the internet. See http://130.241.40.130/hyphe/ or with the proper DNS http://data.thehappysociety.net/hyphe/

I am sure there are smoother ways of doing this. But as a conclusion, the hickup is not with Hyphe at all, but with the way Ubuntu/Apache handles directories outside the default locations. 

Thanks for your comments!

**Comment by boogheta** [comment]
Hi @intensifier 
Looking at your public instance, it looks to me like you installed from the zip release.
This one is actually quite old and we completely rebuilt lots of Hyphe since then in a soon to come release.
So you can either wait a couple more weeks until v0.2 is published as a downloadable zip
If you're in a rush, I'd recommand you install directly from cloning the git repository instead (the bin/install.sh script should do everyhting on itw own)

**Comment by boogheta** [comment]
By the way, I believe the new version installs a more generic apache config (using require from granted ans satisfy any), please let me know if it solves you problems : https://github.com/medialab/hyphe/blob/master/config/apache2_example.conf

**Comment by intensifier** [comment]
@boogheta Thank you very much for the information! It is correct that I installed from the .zip version. I will clone git instead.Right now, my current install works fine, but I will upgrade it to the git version as soon as I get some extra time on my hands. 

Thanks a lot for this!

**Comment by intensifier** [comment]
@boogheta Let me just confirm that installing the version in the git repository worked like a charm. The install script reported no errors and the apache config worked out of the box. Closing this issue now. Cheers!

**Comment by boogheta** [comment]
Hey @christopherkullenberg, I saw on Twitter you've already seen and installed the new version, so just a heads up :)

**Comment by christopherkullenberg** [comment]
Yes, it works like a charm with docker-compose, both on my laptop and on a production server (running ubuntu 16.04). I will use it with my students and perhaps set up a public machine in the near future.
