### ISSUE TITLE
[Front] Menu entries

### ISSUE THREAD

**Issue by annelhote** [medialab/hyphe#119]
The left lateral menu seems not so logical. Why are the "List web entities", "Visualize Network", "Monitor Crawls" links appart from the rest and not included in the menu ?

**Comment by boogheta** [comment]
I also think we should review the whole menu on the left, the CRAWL section has no use and is confusing to users who click on it after defining their webentities losing their WE basket.

I propose to remove the sub-list elements and numbers and use a dedicated icons for each element, and would limit it to the following list and order
OVERVIEW
CRAWL URLS
MONITOR CRAWLS
LIST WEBENTITIES
PROSPECT DISCOVERED
VISUALIZE NETWORK
SETTINGS

@jacomyma @paulgirard @audreybaneyx @pierrejdlf what do you think?

**Comment by annelhote** [comment]
Should PROSPECT DISCOVERED be before LIST WEBENTITIES ? I I usually look at the discovered web entities right after the crawl...

**Comment by RouxRC** [comment]
why not, i was hesitating on this one as well.
And I forgot EXPORT WEBENTITIES between network and settings
