### ISSUE TITLE
Hyphe broken

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#121]
Hi Medialab,

We have just pulled the latest version of hyphe and are now unable to do any crawls. Attached a screenshot of the problem that we encounter with any imported urls. 

![hyphe](https://cloud.githubusercontent.com/assets/745051/7386672/ce4a8d9c-ee56-11e4-9c8d-a0766fa481bd.png)

PS: We have 30 students lined up and ready to play with the tool so any quick help will be greatly appreciated :dancers:

**Comment by boogheta** [comment]
Hi Tobias, did you restart hyphe after pulling? if so it might just be the cache of your browser (shift ctrl r)

**Comment by bornakke** [comment]
Yes it were indeed a cache problem.
