### ISSUE TITLE
Delete old crawls

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#124]
Hi Medialab,

I'm trying to delete old crawls but are unsure how to do it. In the admin interface none of the buttons seem to respond to my clicks. Am I missing something?

Best
Tobias

**Comment by boogheta** [comment]
If you want to delete a corpus, in the admin interface you need first to start it then destroy it, or from the regular interface you just open it then in the settings menu you can destroy it.
If you want to just delete a crawl from a corpus, you cannot for now (and maybe never, this is not decided yet), the logical way is just to set the crawled webentity to out

**Comment by bornakke** [comment]
Solved it. However might a suggest a small info box stating that one have to start the corpus to remove it.

**Comment by boogheta** [comment]
cc @jacomyma
