### ISSUE TITLE
second level domains

### ISSUE THREAD

**Issue by sennierer** [medialab/hyphe#125]
Hi,

thanks very much for sharing this very helpful piece of software!
I recognized in my first test-crawls that hyphe has not a very complete list of second level domains such as "ac.uk" etc. Is there a possibility after a crawl to lets say add "ac.jp" as a second level domain? I saw that its possible to add second level domains to config.json, but can I somehow "re-explore" the links once I have added new second level domains without crawling all the pages again?

Thanks very much!

Matthias

**Comment by bornakke** [comment]
I think you can added it to the config.json file under creationRules. However I have as you experienced that the standard list is really missing quite a lot of names.

**Comment by sennierer** [comment]
Thanks very much. I already saw that...my problem is that I am exploring these missing second level domains while running through the explored web entities and I dont want to crawl all the sites again. However, for the moment I am just manually generating new web entities out of the second level domains.
Something else that came to my mind: Do you know how or if I can add a creation rule for all "gov" second level domains? Is it possible to use regexp type wild cards such as "gov\..*"?

**Comment by boogheta** [comment]
Hi @sennierer
Yes this is something we ought to fix in the future by including mozilla's list of TLDs in the backend, but in the mean time, you can either:
- if you install hyphe on your machine, just add the second level domains you need in the global config like here: https://github.com/medialab/hyphe/blob/master/config/config.json.example#L42 (I actually added ac.uk yesterday but it'is not in the demo yet), more explanations can be found in the documentation here https://github.com/medialab/hyphe/blob/master/doc/config.md (look for creationRules)
- on an individual corpus in the demo you cn alternatively navigate to the Ac.uk webentity (search it in list of webentites then click on the small faint circle next to the name) and explore urls. Then you can set an autiomatic rule for each newly found url under a specific prefix such as ac.uk

**Comment by boogheta** [comment]
PS: @Bornakke please complete the list in the default config with a pull request :D

**Comment by sennierer** [comment]
Thanks very much! The links are very helpful!
I have another question that might be a bit stupid, but I couldnt find the answer...: what exactly is stored in the body fields of the mongodb PROJECT.pages? Is it the actual html body of the page compressed somehow?

Thanks very much!

Matthias

**Comment by boogheta** [comment]
yes this is the raw html (or the exported dom as html when crawling with phantomjs) compressed as gzip. In the long term we want to do text indexation of the contents, we have a sample project trying to do that with solr here: https://github.com/medialab/hyphe2solr

**Comment by boogheta** [comment]
PS: and this is one of the reasons a corpus can quickly make the mongodb grow quite a lot :)

**Comment by sennierer** [comment]
I see! Thanks very much again!


matthias
