### ISSUE TITLE
[front] [prospect] set to in|out|und button: confusing

### ISSUE THREAD

**Issue by pierrejdlf** [medialab/hyphe#129]
how to submit my choice(s) ?

on the right panel:
i guess that if i click CRAWL on the right, it will set the selected entities to IN and CRAWL them

for OUT/UND, there is also a CRAWL button... is that normal ?

**Comment by pierrejdlf** [comment]
ok i understood
don't need to submit, clicking on one of the IN / OUT / UND button is enough to update entity

but it's a little confusing
the right panel acts as if we need to confirm the choices made on the list

ideas:
- set all buttons from the list to UND. active state by default ?
- (fake?) 50ms waiting time between the click and... a changing color for the clicked button (green?)
- remove the "SET TO..." prefix from the right panel ?

**Comment by boogheta** [comment]
Hey Pierre,

Setting things to UNDEFINED by default would be problematic as they need to stay DISCOVERED as long as the user didn't review them yet.

I wanted to remove the CRAWL button for the UNDEFINED and OUT boxes for a while, will do that and change "SET TO" to "ADDED TO" which expresses better the action was performed and does not need to be done afterwards anymore.

Let me know if you think this solves it
