### ISSUE TITLE
Hyphe cannot deploy crawler on Ubuntu 14.04

### ISSUE THREAD

**Issue by kai17** [medialab/hyphe#139]
Using the pre-built tarball for revision 0.2, I cannot run hyphe unter Ubuntu 14.04 (Trusty). I have removed all instance of scrapy/scrapyd before running the installation script. I have also tried to reinstall the packages from the same ppa that your installation uses. Still, scrapyd will not run because it misses txweb (this seems to be a recurring issue). After additionally installing scrapy-deploy from the ppa as well as scrapy-jsonrpc, running this testscript (minus the manual start of scrapyd) works fine: https://github.com/scrapy/scrapyd/blob/master/extras/test-scrapyd.sh 
I also tried manually installing these packages with pip: https://github.com/medialab/hyphe/blob/master/doc/install.md#23-install-scrapyd
However, either way hyphen fails with this string of error messages:

Would packaging an older version of scrapy/scrapyd help?

015-06-22 16:52:32+0200 [-] Log opened.
2015-06-22 16:52:32+0200 [-] twistd 15.2.1 (/home/kai/.virtualenvs/hyphe/bin/python 2.7.6) starting up.
2015-06-22 16:52:32+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-06-22 16:52:32+0200 [-] Site starting on 6978
2015-06-22 16:52:32+0200 [-] Starting factory <twisted.web.server.Site instance at 0x7f6ce4469c68>
2015-06-22 16:52:34+0200 [ERROR - --test-corpus--] Couldn't deploy crawler
2015-06-22 16:52:34+0200 [-] Received SIGTERM, shutting down.
2015-06-22 16:52:34+0200 [-] (TCP Port 6978 Closed)
2015-06-22 16:52:34+0200 [-] Stopping factory <twisted.web.server.Site instance at 0x7f6ce4469c68>
2015-06-22 16:52:34+0200 [-] ERROR [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
2015-06-22 16:52:34+0200 [-] ]
2015-06-22 16:52:34+0200 [-] Main loop terminated.
2015-06-22 16:52:34+0200 [-] Server Shut Down.

**Comment by boogheta** [comment]
Hi,

I don't completely understand your bug report: you say scrapyd does not work because it misses txweb but the test-scrapyd.sh script works?

Do you have anything at http://localhost:6800/listprojects.json ?

Can you give me the outputs of:
```bash
bin/deploy_scrapy_spider.sh test
pip freeze
source /usr/local/bin/virtualenvwrapper.sh
workon hyphe
pip freeze
aptitude search scrapy
```

**Comment by kai17** [comment]
Hi, this is my laptop (Ubuntu 14.04, 32bit. I cannot access my office PC
from home (14.04, 64bit):


test-scrapyd.sh works after installing scrapyd-deploy and copying over
txweb.py

This is was I get from http://localhost:6800/listprojects.json

{"status": "ok", "projects": ["testproj", "hyphe.dodgy"], "node_name": "zaphod"}

The deploy script does not work:
> $ bin/deploy_scrapy_spider.sh
test

Copying config.json from root directory to hyphe_backend/crawler for scrapy
deployment...
WARNING: trying to deploy a crawler for a corpus project missing in DB
Importing urllru.py library from HCI hyphe_backend/lib to hcicrawler...
Rendering settings.py with mongo-scrapy config values from config.json...
Rendering scrapy.cfg with scrapy config values from config.json...
Sending HCI's scrapy egg to scrapyd server...
There was a problem sending the scrapy egg.
Scrapy 1.0.0rc3.post2+g2ff9888 - project: hcicrawler

Unknown command: deploy

Use "scrapy" to see available commands


pip freeze fails:
> $ pip
freeze

Exception:
Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py",
line 134, in main
    status = self.run(options, args)
  File
"/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/commands/freeze.py",
line 73, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links,
find_tags=find_tags)
  File
"/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/__init__.py",
line 194, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing complete log in /home/kai/.pip/pip.log

But it seems to work ok within the virtualenv:
kai@zaphod
~/hyphe
[20:31:28]
> $ source
/usr/local/bin/virtualenvwrapper.sh



kai@zaphod
~/hyphe
[20:32:20]
> $ workon
hyphe



kai@zaphod
~/hyphe
[20:32:35]
(hyphe)> $ pip
freeze

Twisted==15.2.1
argparse==1.2.1
cffi==1.1.2
characteristic==14.3.0
cryptography==0.9.1
enum34==1.0.4
idna==2.0
ipaddress==1.0.7
pbr==1.1.1
pyOpenSSL==0.15.1
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.14
pymongo==2.7
pystache==0.5.4
selenium==2.42.1
service-identity==14.0.0
simplejson==3.7.3
six==1.9.0
stevedore==1.5.0
thrift==0.9.2
txJSON-RPC==0.3.1
txmongo==0.6
virtualenv==13.0.3
virtualenv-clone==0.2.5
virtualenvwrapper==4.6.0
wsgiref==0.1.2
zope.interface==4.1.2

Finally, this is what I get from aptitude:

kai@zaphod
~/hyphe
[20:32:40]
(hyphe)> $ aptitude search
scrapy

p
python-scrapy
- Python web scraping and crawling
framework

p
python-scrapy-doc
- Python web scraping and crawling framework
documentation
v
python2.7-scrapy
-

i A
scrapy
- Python web crawling and web scraping
framework

p
scrapy-0.14
- Python web crawling and scraping
framework

p
scrapy-0.15
- Python web crawling and scraping
framework

p
scrapy-0.16
- Python web crawling and scraping
framework

p
scrapy-0.17
- Python web crawling and scraping
framework

p
scrapy-0.18
- Python web crawling and scraping
framework

p
scrapy-0.19
- Python web crawling and scraping
framework

p
scrapy-0.20
- Python web crawling and scraping
framework

p
scrapy-0.21
- Python web crawling and scraping
framework

p
scrapy-0.22
- Python web crawling and scraping
framework

p
scrapy-0.23
- Python web crawling and scraping
framework

p
scrapy-0.24
- Python web crawling and scraping
framework

p
scrapy-0.25
- Python web crawling and screen scraping
framework
i
scrapyd
- Scrapyd
server

p
scrapyd-0.14
- Scrapy
Service

p
scrapyd-0.15
- Scrapy
Service

p
scrapyd-0.16
- Scrapy
Service

p
scrapyd-0.17
- Scrapy
Service

i
scrapyd-deploy
- Scrapyd deployment
tool

p
scrapyorg
- scrapy.org website

Hope that helps.
Best,
Kai

**Comment by kai17** [comment]
As a follow-up,  I think the scrapy people have recently rolled the deploy
command into a separate program.  Could this be the problem?

**Comment by boogheta** [comment]
I think you're having conflicts between different versions of scrapy/scrapyd indeed. It looks like the "scrapy deploy" command was removed from scrapy-0.25 and replaced with scrapyd-deploy
We should probably handle this for the future, thanks for the report.
Your options are the following:
- either deal with the mess of removing cleanly (using apt-get remove --purge <package>) all scrapy parts from your machine, then reinstall pinned versions scrapy-0.24 & scrapyd-0.17
- or go and change manually the call to the deploy command in hyphe_backend/crawler/deploy.py, line 93, change:
`subprocess.Popen(['scrapy', 'deploy', '--version'`
into:
`subprocess.Popen(['scrapyd-deploy', '--version'`

**Comment by kai17** [comment]
Thank you very much for your quick reply. Pinning did the trick, and I'm happily crawling now. You really made my day!

Best,
Kai
Benjamin Ooghe-Tabanou writes:

> I think you're having conflicts between different versions of scrapy/scrapyd indeed. It looks like the "scrapy deploy" command was removed from scrapy-0.25 and replaced with scrapyd-deploy
> We should probably handle this for the future, thanks for the report.
> Your options are the following:
> - either deal with the mess of removing cleanly (using apt-get remove --purge <package>) all scrapy parts from your machine, then reinstall pinned versions scrapy-0.24 & scrapyd-0.17
> - or go and change manually the call to the deploy command in hyphe_backend/crawler/deploy.py, line 93, change:
> `subprocess.Popen(['scrapy', 'deploy', '--version'`
> into:
> `subprocess.Popen(['scrapyd-deploy', '--version'`
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/medialab/hyphe/issues/139#issuecomment-114430050

-- 
Professor of Politics
Institut für Politikwissenschaft / JGU
http://www.kai-arzheimer.com / @kai_arzheimer
Read: 'The AfD: Finally a Successful Right-Wing 
Populist Eurosceptic Party for Germany?' http://is.gd/ka_afd
