### ISSUE TITLE
"network" page data not up to date

### ISSUE THREAD

**Issue by jacomyma** [medialab/hyphe#146]
In some cases (ex: SOURCE corpus on demo) the status and "cited by" count of some entities is not up to date. We think it might be a cache issue.

Ex : an entity has a status "DISCOVERED" in the "network" page while it is "IN" in the "list" page and in the "prospect" page as well (absent from the prospect). It happens for many entities at the same time, as if some updates were not propagated.

**Comment by boogheta** [comment]
should have been fixed along with #160
