### ISSUE TITLE
Scrapyd Port

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#153]
Hi Medialab,

We are installing hyphe on a new and bigger ubuntu server. However during the install we keep geting the following error:

Install and start ScrapyD...
----------------------------

...already installed...
...setting config...
bin/install.sh: line 151: 18623 Killed                  sudo pkill -9 -f scrapyd
...restarting daemon...
scrapyd start/running, process 18632
...testing...
Could not start ScrapyD server properly. Please check your install

I'm thinking that this might be due that all the ports - except port 80 - are currently closed. Does that sound like a reasonable reason? And if yes, which ports should I ask the server admin to open up for hyphe to work probably?

Best
Tobias

**Comment by boogheta** [comment]
Hi Tobias, nope this is due to @Scrapy who broke their repositories (see https://github.com/scrapy/scrapyd/pull/114 ) 
I was hoping they would fix it (they just need to update their ubuntu repository to the latest release) but it's taking forever.

@bornakke are you installing from git source or from our latest release? I've just pushed a temporary fix in the install in the master source. Otherwise if from the release, you should run sudo apt-get install scrapy-0.24 before you rerun the script.

**Comment by bornakke** [comment]
Made a pull, but same error. Also I'm getting this error which wasn't there before: 

W: GPG error: http://ftp.iitm.ac.in trusty/ Release: The following signatures were invalid: KEYEXPIRED 1445181253 KEYEXPIRED 1445181253 KEYEXPIRED 1445181253
 ...installing packages...

Add source repositories...
--------------------------

 ...updating sources repositories...
W: GPG error: http://ftp.iitm.ac.in trusty/ Release: The following signatures were invalid: KEYEXPIRED 1445181253 KEYEXPIRED 1445181253 KEYEXPIRED 1445181253

**Comment by boogheta** [comment]
I don't know what ftp.iitm.ac.in corresponds to, this does not look like anything related to hyphe, I guess this is something you installed separately in your apt sources.list
Regarding your scrapy issue, can you come over on #medialab's IRC (irc.freenode.net) ?

**Comment by bornakke** [comment]
I'm there now - however I don't remember what your nickname is :)

**Comment by boogheta** [comment]
Hey @bornakke, everything good now?

**Comment by bornakke** [comment]
yes - and thank you very much for the quick response.

**Comment by c24b** [comment]
+1 Same error on release 0.2

**Comment by boogheta** [comment]
@c24b can you be more explicit as TObias had two different issues here? or reopen your own issue with copies of your errors?

**Comment by boogheta** [comment]
Hey @c24b, FYI, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe with ScrapyD now.
