### ISSUE TITLE
[Doc_typo?] Missing parameter in doc for the crawl_webentity function

### ISSUE THREAD

**Issue by legaultpierre** [medialab/hyphe#155]
In this [doc](https://github.com/medialab/hyphe/blob/master/doc/api.md#basic-crawl-methods) it is said for the `crawl_webentity` function that it takes 6 arguments (webentity_id, depth, phantom_crawl, status, phantom_timeouts, corpus).

However, in this [working example](https://github.com/medialab/hyphe/blob/master/bin/samples/start_crawling_webentities_from_csv/start_crawling_webentities_from_csv.py#L57), we can see a string parameter (`'prefixes'`) between the `status` and `phantom_timeouts` parameters.

Without this additional and unknown parameter, the crawling does not work.

Probably a typo in the doc?

**Comment by boogheta** [comment]
due to an instance not up to the latest updates
