### ISSUE TITLE
Start hyphe on system reboot

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#156]
We use crontab to start hyphe whenever the system is rebooted with the following code:

@reboot /dir/to/hyphe/bin/hyphe restart

However after migrating to another server this have stopped working. Might be something with the system. Just wanted to know if you had any prior knowledge of such issues?

Best regards
Tobias

**Comment by boogheta** [comment]
A lot of things can be different on another server :)
Do you have cron installed already?
If your server can send e-mails, you can try to debug crons by adding a .forward file containing just one line with your e-mail in the HOME directory of the user. The logs of each cron job will be sent out to your mailbox

**Comment by bornakke** [comment]
Got it to work.
