### ISSUE TITLE
Unable to launch a crawl

### ISSUE THREAD

**Issue by Dafaka** [medialab/hyphe#159]
Hi

Since our last contact I had no opportunity to move forward on Hyphe because I had to change my work machine .

I have now installed hyphe 0.2 on debian 7.9.
Everything went well during the installation and launch of Hyphe is ok.  I create a first corpus today.
Unfortunately, after entering my starting url and launched an initial crawl , I have a warning ( 1 web entity to check) . My problem is that I can't type anything in the correction area provided for this purpose (Enter url or type) because it is not active ...

![capture](https://cloud.githubusercontent.com/assets/6612986/12116647/a483eed8-b3bb-11e5-8276-cc0cb208bb4d.jpg)

Forcing the crawl ( crawl schedule ) my list of prospects well fed , but it is impossible to explore an entity ( entity Error loading web ) ...

I have this errors in the console logs :
```
2016-01-05 14:14:13+0100 [HTTPChannel,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/var/www/hyphe/hyphe_backend/core.tac", line 79, in render
	    return jsonrpc.JSONRPC.render(self, request)
	  File "/home/dafaka/.virtualenvs/hyphe/local/lib/python2.7/site-packages/txjsonrpc/web/jsonrpc.py", line 110, in render
	    d = defer.maybeDeferred(function, *args)
	  File "/home/dafaka/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/dafaka/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/home/dafaka/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
	    result = g.send(result)
	  File "/var/www/hyphe/hyphe_backend/core.tac", line 1645, in jsonrpc_get_webentities
	    sublists = [list_ids[MAX_WE_AT_ONCE*i : MAX_WE_AT_ONCE*(i+1)] for i in range((n_WEs-1)/MAX_WE_AT_ONCE + 1)]
	exceptions.TypeError: range() integer end argument expected, got float.
```

Please have you an idea of ​​the error ( configuration , other? )
Thank you
Dafaka.

**Comment by boogheta** [comment]
Hi @Dafaka and yes, this is a known issue that was fixed in the code. Did you install from the release zip? If so I should definitely build a new zip with this error fixed the soonest.
In anycase, you should be able to solve your issue by applying the three modifications visible here: https://github.com/medialab/hyphe/commit/7a6efd23d106b4758849913971370b53f401723e

**Comment by Dafaka** [comment]
Hi @boogheta 
I installed from hyphe-release-v0.2.tar.gz 
I applied the modifications and it's ok now.
Thank you.

**Comment by boogheta** [comment]
Great thanks, I'm reopening it to remember and fix the release although :)

**Comment by boogheta** [comment]
Hi @Dafaka , FYI, we finally released a new version with plenty new features, including a more generic installation process which should allow you to easily install Hyphe now.
