### ISSUE TITLE
Package brokken on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#169]
Hi Medialab,

I'm starting a new issue since I have now become convinced that the problem with my crawls failing is linked to some greater incompatability between ubuntu and hyphe.

I have today attempted to setup hyphe (hyphe-release-v0.2.1.tar.gz) on two different completely fresh ubuntu machines. One local physical server and one at digital ocean. Both installs however failed with the same error:

...setting config...
bin/install.sh: line 151: 11926 Killed                  sudo pkill -9 -f scrapyd
...restarting daemon...
scrapyd start/running, process 11935
...testing...
Could not start ScrapyD server properly. Please check your install

There are no log file in the log directory and no errors in the install.log. Only indication of an error is Pip freeze which returns some weird strange numbers for scrapy etc.:
http://pastebin.com/E5PeQLWy

Since I'm now working on another machine I can provide you with ssh access if you need somewhere to test?

Best
Tobias

**Comment by boogheta** [comment]
All right, so I hereby declare you my official remote beta tester for ubuntu releases ;)
Can you try out with this beta archive of a v0.3 : http://jiminy.medialab.sciences-po.fr/data/hyphe-release-v0.3.tar.gz

**Comment by bornakke** [comment]
Tried it on a new completly fresh install:

The install got further. It now however dies with the following error in the install.log:

[...] 
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/temp.linux-x86_64-2.7/simplejson$

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2$

running install_lib

creating /usr/local/lib/python2.7/dist-packages/simplejson

error: could not create '/usr/local/lib/python2.7/dist-packages/simplejson': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_bornakke/simplejson/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __f$
Storing debug log for failure in /home/bornakke/.pip/pip.log

**Comment by boogheta** [comment]
need more context, can you paste the whole `install.log` and `/home/bornakke/.pip/pip.log` somewhere?

**Comment by bornakke** [comment]
Install.log
http://pastebin.com/M9DTNjXW

Pip.log:
[pip.txt](https://github.com/medialab/hyphe/files/187682/pip.txt)

**Comment by boogheta** [comment]
@bornakke I don't understand how your install.log can be so short, you crash at line 227 of `install.sh` but the last output I see in your `install.log` corresponds to line 107

Also are you sure this is a completely fresh new install? Your log indicates that everything was already installed which is quite surprising for at least a few dependencies. Are you sure this was not a machine on which you tried already to install? Or that is it really the good install.log and not one from a previous tryout?

But this being said, basically the issue that rises here is that it tries to install hyphe's python-pip dependencies globally instead of within hyphe's dedicated virtualenv. So I can only assume that the creation and/or activation of the virtualenv failed (but I don't see any relative log).
To try and identify why it is a such, can you try by hand the following command and give me their outputs?

```bash
which virtualenvwrapper.sh
find /usr/ -name "virtualenvwrapper*"
source /usr/local/bin/virtualenvwrapper.sh
source /usr/bin/virtualenvwrapper.sh
lsvirtualenv
mkvirtualenv --no-site-packages test
workon test
```

PS: I could use the standard output on your machine as well as a complement. ssh access would be nice too indeed

**Comment by bornakke** [comment]
Hi Boogheta,

Firstly i'm completly sure this is a fresh machine, since the old virtual machine were deleted before booting this one. Like you I were however also surprised by few/missing entities in the install log.

Secondly the problem with virtualenv make sense since I for now some time have gotten errors and warnings from virtualenv on all machines I have attempted to install hyphe on. Seem that the very very common and normal harmless perl locale error, that makes the install of virtualenv fail:

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C"). 

I then setup another fresh machine and fixed this issue with below calls:
export LANG="en_US"
export LC_ALL=$LANG.UTF-8
sudo dpkg-reconfigure locales

I were then able to conclude the installation with only below two warnings:
/home/bornakke/.virtualenvs/hyphe/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/bornakke/.virtualenvs/hyphe/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Hyphe then started, but when I started a crawl the scrapy error we saw at the other machine were back:
http://pastebin.com/0Qke5901

I will see if can catch you on IRC to provide you with SSH. What is your username?

Best
Tobias

**Comment by boogheta** [comment]
Hey!

Yes, while testing it on different machines as well, I encountere the same locales issue, not sure why this arose and I feel like this is so machine specific that hyphe's installer shouldn't try and mess with this, I'll rather add a specific point on this in the documentation I guess...

So we're back onto the insecure ssl thing, ok, will keep investigating it tomorrow and hopefully we'll have a usable v0.3 soon :)

Sorry I missed your passage on irc, for a user account I'll be happy with boogheta or boo. I can send you by e-mail my public ssh key if that avoids you having to give me a password, otherwise wait until we meet on irc and i'll change it immediately afterwards

**Comment by boogheta** [comment]
By the way, did you get any more success with the docker install ?

**Comment by bornakke** [comment]
Haven't tried that yet but I will probably give it a try in a few days if v0.3 does not solve it.

The locale issue have been very common on ubuntu for the last several years. I actually don't have a single server which didn't come with it upon first boot. I think your idea of placing it in the documentation is good, but one could also consider to make the install script check if locale is set and then print a warning if it isn't.

**Comment by bornakke** [comment]
Any news with this?

**Comment by boogheta** [comment]
Hey Tobias sorry for the delay, had to switch to other priorities. I hope to get the time to work on rlz v0.3 next week

**Comment by bornakke** [comment]
We have just had a man put up Hyphe through Docker which works so we will survive with this setup for now. I'm however leaving this ticket open since the old way of installing it is by far the easiest way.

Greetings to France

**Comment by bornakke** [comment]
@boogheta Could you come to IRC? Docker install is not working very well :(

**Comment by boogheta** [comment]
good news about your docker success, let me know if you run into new errors, and I'll be curious to know about your issues with centos

**Comment by boogheta** [comment]
Hi @bornakke !

FYI, we are in the process of rebuilding a lot of things (cf branch named traph) so we won't be maintaining installation of the actual master branch and will provide an easier install in the coming months, so I'm closing install related issues as of now, but feel free to continue reporting/asking questions in the thread.
