### ISSUE TITLE
Add prefixes for mobile/national social media sites to default config.json

### ISSUE THREAD

**Issue by kai17** [medialab/hyphe#171]
Out of the box, hyphe recognises http(s)://www.facebook.com and http(s)://facebook.com as equivalent, but there is also http(s)://m.facebook.com and even http(s)://de-de.facebook.com. For non-experts, it is not obvious from the wiki/documentation  how this should be reflected in config.json

**Comment by boogheta** [comment]
Hi @kai17, Hyphe lets you define thresholds for accounting a same website, for instance to a domain, a subdomain, a subpath, etc.
By default the config.json provides those two lines
```
"facebook.com": "path-1",
"facebook.com/pages": "path-2",
```
They result in considering individual websites for each facebook page (with it variations of http/https ans www or not).
If you want to group all facebook pages together, including all subdomains, you can replace them with 
```
"facebook.com": "domain",
```
Although there is no easy way of hacing at the same time the split into multiple entities per facebook page and the grouping of the subdomains. So you'll have to choose for the default behavior between these two.

You can always manually adjust the limits of individual entites afterwards in your corpus using the Merge in the WebEntitiesList and the "Define new" option in the "Explore pages" tab of a WebEntity (clicking on the faint icon next to a webentity in any list)

**Comment by kai17** [comment]
Hi Benjamin,
thanks for that. This part is clear from the documentation, but I'm looking
for a way to keep the "path-1" / "path-2" behaviour while ignoring/grouping
together all subdomains (mobile, www, m, de-de etc.). Is that even possible?

**Comment by boogheta** [comment]
It is not possible as a default behaviour rule for each new one. You can adjust them manually a posteriori from the web interface or the API, but not set a rule for such kind of webentities as it does not correspond to a common LRU prefix.

We are thinking about rebuilding our memorystucture in ways that might allow that in the future but it currently isn't possible as a systematic rule.

Although, if you're coding a little bit, this can easily be done with a python script dialoguing with the API at the end, meaning, after having built the whole corpus, reconsolidate splitted facebook profiles as individual ones by querying all of these webentities via the search route, then assembling them algorithmically and finally sending to the API grouped merges.
You can read the API documentation here <https://github.com/medialab/hyphe/blob/master/doc/api.md> and such sample python script there <https://github.com/medialab/hyphe/blob/master/bin/samples/start_crawling_webentities_from_csv/start_crawling_webentities_from_csv.py>
Let me know if you're interested with this option and I can try and help you towards this purpose.

**Comment by kai17** [comment]
Thanks a lot for your quick reply, and more generally, thank you for
developing and supporting Hyphe, which is a great tool!

Solving the problem by accessing the API sounds great, but I'm afraid
that's beyond our abilities. We'll try to solve the problem manually this
time.

Best wishes,
Kai
