### ISSUE TITLE
Error on the release page

### ISSUE THREAD

**Issue by joelgombin** [medialab/hyphe#172]
The installation instructions read:

`tar xzvf hyphe-v0.2.tar.gz`

where it should be:

` tar xzvf hyphe-release-v0.2.1.tar.gz`

Other than that, the install works great on Ubuntu, thanks a lot!

**Comment by boogheta** [comment]
Indeed thanks for the feedback!
btw can you let me know which ubuntu version you used?

**Comment by joelgombin** [comment]
It worked fine on an Ubuntu server 12.04.5.
On my desktop Ubuntu 14.04.4, though, I got a problem with scrapyd not starting correctly. Tried to uninstall/reinstall, hyphe still didn't want to complete the installation.

**Comment by boogheta** [comment]
All right, thanks it confirms our experiences. A new v0.3 release will come soon to fix this

**Comment by boogheta** [comment]
Hey @joelgombin, I believed you've seen it already on Twitter, but just in case, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe with ScrapyD now.

**Comment by joelgombin** [comment]
\o/ you rock, guys!
