### ISSUE TITLE
Display WebEntities ID in lists

### ISSUE THREAD

**Issue by debcarpe** [medialab/hyphe#175]
J'ai un problème, dans ma liste de sites, quelques webentities on le meme titre, allors, c'est difficile de catégoriser, je voudrais que le ID puisse apparaître aussi dans la liste de webentities, pour vérifier plus facilement si c'est un double ou un autre site... merci!

**Comment by boogheta** [comment]
can probably be better addressed by including TLDs into WebEntities names.

**Comment by debcarpe** [comment]
TLD and ID number is the same?

**Comment by boogheta** [comment]
no TLDs are .fr .eu .co.uk etc, which are currently stripped from the names but could get back in which would solve your problem

**Comment by boogheta** [comment]
As said by e-mail, in the mean time, you can use the ID visible in the url, cf screenshot: 
![hyphe](https://cloud.githubusercontent.com/assets/1822297/15499991/082873d8-21a7-11e6-905e-d20ee67865a6.png)

**Comment by debcarpe** [comment]
I believe that include TLD into WebEntities names is a great idea, we recognize the multiple nature within each actant.
But, the way to visualize ID  is not very pratique because we can only see this when mouse is over, and if I want to copy it I need to open other page... and let the page "webentities list" and loose the "exact" page list where I was before*. I agree that the best think is create a new column for ID in the webentities liste, after "last modification" column (maybe optional - mode on off)
Another suggestion:
*To find a exact int the sommaire nº of a page in the webentities is very hard, you can imagine how I do to go exactly to page nº 42... e.g. ? :-) I suggest an option "go to page..." and choose a list with 50 webentities ou customise
![sommaire](https://cloud.githubusercontent.com/assets/6041619/15500550/77afbc0a-21a9-11e6-981f-75d0073a31cf.png)
