### ISSUE TITLE
Troubles to install hyphe-release-v0.2.1.tar.gz

### ISSUE THREAD

**Issue by uelramon** [medialab/hyphe#177]
Hello,

I am trying to install Hyphe v0.2.1 on a virtual machine with ubuntu 14.04. What i could understand of this versions of hyphe is that is possible to use without a server, is that right?

So, the installation process can not be complete resulting in this information on the install.log. Did anyone has a way to install hyphe to use without a server? I need to use in my home.

Thanks!!

Install.log message:

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/main/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/restricted/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/universe/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/multiverse/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/restricted/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/universe/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/multiverse/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/restricted/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/universe/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic/multiverse/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/main/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/main/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/main/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/main/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/restricted/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/universe/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/multiverse/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://security.ubuntu.com/ubuntu/dists/utopic-security/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/main/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/restricted/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/source/Sources  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/main/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/restricted/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/binary-amd64/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/main/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/restricted/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/binary-i386/Packages  404  Not Found

W: Falhou ao buscar http://br.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/binary-i386/Packages  404  Not Found

E: Falhou o download de alguns ficheiros de índice. Foram ignorados ou os antigos foram usados em seu lugar.

**Comment by boogheta** [comment]
Hi there,

Hyphe requires a backend daemon that runs at all times, hence a server, but a local machine that you keep up at home works as well.

There are some issues with releases v0.2.x that Im currently fixing in a soon to come v0.3. You can try a beta version available that was tested on a fresh new ubuntu 14.04.5 LTS here : http://jiminy.medialab.sciences-po.fr/hyphe-release-v0.3.tar.gz

Although, it seems like you have weird package repositories set in your ubuntu installation (you are relying on utopic which is 14.10 and not maintained anymore (hence the 404 you get with apt-get update) when it should rather be trusty which as a LTS is maintained for a couple more years).. We only support LTS versions of Ubuntu. You should check your install and maybe edit/fix your /etc/apt/sources.list or setup a new VM

**Comment by uelramon** [comment]
Thanks for the quick answer Mr. Benjamin.

I will try to reinstall the ubuntu LTS version just for ensure, and in the next i will install the Hyphe v0.3.
I'll publish here the results.

Thank you again!

**Comment by uelramon** [comment]
Hello again Mr Benjamin.

I finally succeeded in installing hyphe in Ubuntu 14.04 LTS, but the system is online only a few minutes, not enough to initiate the procedures for a search.

Could you tell me what I can do in this case?

Thank's a lot.
Ramon.

**Comment by boogheta** [comment]
Hi @uelramon,
I'm not sure I understand what happens. Could you tell me a little bit more, pasting the logs from log/hyphe-core.log for instance?

**Comment by uelramon** [comment]
Hello Mr. @boogheta ,

I installed the both versions of hyphe, 0.2 and 0.3, and each one has an issue.

**The version 0.3**: i installed and run hyphe in the terminal following the guide here in Github, and when i command bin/hyphe start i get the message that the program run normally, but only for a few seconds. I post the screen shot to help.

Commands on Terminal:
![hyphe 03](https://cloud.githubusercontent.com/assets/739808/16150233/55dcca7a-346c-11e6-81ac-aad9193d93ad.png)

Hyphe login on localhost/hyphe:
![hyphe 03 login](https://cloud.githubusercontent.com/assets/739808/16150209/3651dfb0-346c-11e6-85ff-baccf2f570bf.png)

Hyphe disconnected after a few seconds of the connection:
![hyphe 03 off](https://cloud.githubusercontent.com/assets/739808/16150208/364904b2-346c-11e6-9bc8-70cbe365e777.png)

Here's the log of the Hyphe v0.3:
[hyphe-core v.03.txt](https://github.com/medialab/hyphe/files/320399/hyphe-core.v.03.txt)

**The version 0.2**: in this version i have more advances. I can access the hyphe without the problem of disconnect, importing URL's with success and defining then as web entities. But the problem begin in the crawling process. When i choose one web entities to crawl, clicking in Schedule crawls, the system exit the project without crawling. When i enter again in the same project there is no crawl activity running or in the history. 

Another problem is related with the Network function. When i click in this button the system stay Loading Network and never build the net. I'm trying in one project with 105 web entities.

This is the log of the version 0.2:
[hyphe-core v.02.txt](https://github.com/medialab/hyphe/files/320398/hyphe-core.v.02.txt)

I hope I have been able to clarify this issues. I do not have much knowledge about programming, but I'm reading all hyphe documents to better understand its functioning.

Thank you again Mr. @boogheta .

**Comment by boogheta** [comment]
All right, I understand what happens with your v0.3, although I don't get why it happens on your machine and not on mine. This is due to the way logs are printed out since twisted version 16. Just downgrading to Twisted 15.5 should solve it, you can do it as such:
```bash
source $(which virtualenvwrapper.sh)
workon hyphe
pip install Twisted=15.5
deactivate
bin/hyphe restart
#might need to run it a second time if it first says it failed stopping
```

Was thinking for v0.3 about restricting to twisted 15, I guess your experience confirms I should until better investigation

**Comment by uelramon** [comment]
Mr @boogheta , I did the downgrade to Twisted 15.5  and could access the hyphe without going offline. But hyphe dont recognize no url when trying to create a web entitie, as in the screen-shot:
![captura de tela de 2016-06-17 16 22 50](https://cloud.githubusercontent.com/assets/739808/16162963/03a55128-34ad-11e6-8168-ab53a71d2c8e.png)
 
And after that when I click on any of the buttons (Crawl, Web Entities, Network, Export, Settings) there is an error message:
![captura de tela de 2016-06-17 16 22 58](https://cloud.githubusercontent.com/assets/739808/16163024/5ef06496-34ad-11e6-8857-2de710e18acd.png)

I'm trying in another machine, more faster (Core i5 and 4gb ram) and with a dualboot (windows 10 and ubuntu 14.04 lts), but the result is the same.

**Comment by boogheta** [comment]
Looking at your screenshots it looks like you are trying to work using the --test-corpus-- which as the names indicates is a test coprus that is created and destroyed at each hyphe restart. So I imagine you opened it as soon as it appears when you restarted and then it detroyed it automatically while you were trying to use it. You should create your own corpus instead from the /#/login page

**Comment by uelramon** [comment]
This problem occurs on any project/corpus. All the buttons are inaccessible, even the Setting button.

![Uploading Captura de tela de 2016-06-20 14:07:43.png…]()
![captura de tela de 2016-06-20 14 07 58](https://cloud.githubusercontent.com/assets/739808/16203405/7a1dbfc6-36f0-11e6-97c2-f78d53807052.png)

**Comment by boogheta** [comment]
Strange.
Can you paste the output of your browser's console? screenshots are not much informative :)

**Comment by uelramon** [comment]
Sorry Mr. @boogheta !!

Here comes the info from browser's console.

Hyphe's log:
[hyphe-core.txt](https://github.com/medialab/hyphe/files/325581/hyphe-core.txt)

I think that is the output from brownser's console, is that it? Sorry by the big screenshot, i think its better to read.
![log](https://cloud.githubusercontent.com/assets/739808/16229841/e860e266-3794-11e6-91bf-98ed4bb8bbe6.png)

**Comment by boogheta** [comment]
Thanks (although, since this is text, you could have just copy-pasted them instead of making multiple screenshots ;) )rself
I don't really get why your machine bhaves like this, but it looks to me like the fix didn't solve the issue indeed and your machine drops log messages sent directly to stdout

I tried to propose a correction, but I cannot be sure it actually works without you trying it yourself : so can you download the file at https://raw.githubusercontent.com/medialab/hyphe/master/hyphe_backend/core.tac and replace your hyphe_backend/core.tac file with it?
```bash 
wget https://raw.githubusercontent.com/medialab/hyphe/master/hyphe_backend/core.tac -O /home/ramon/Documentos/hyphe/hyphe_backend/core.tac
```

**Comment by uelramon** [comment]
Mr @boogheta , i did as you say but the problem keeps:

ERROR: Could not start Hyphe's backend server properly.

For a very few seconds hyphe runs normally, but in the crawling process everything stops.

I'm trying in two machines, a Dell Vostro 5470 (i5 and 4 mb ram) and one old HP dual core, both with the same OS - Ubuntu 14.04 LTS. You recomend another OS?

**Comment by boogheta** [comment]
can you give me the core logs again ?
ubuntu 14.04 should be fine normally, I understand what happens, but I don't know why, investigating...

**Comment by uelramon** [comment]
Here they are:
[hyphe-core.txt](https://github.com/medialab/hyphe/files/325838/hyphe-core.txt)

**Comment by boogheta** [comment]
OK, I still don't get why it behaves like this for you and never happened on any other machine I had but I understand what happens. I unfortunately don't have the time right now to try and handle it, but here's a hotfix that should fix it just for you, just download the file at http://jiminy.medialab.sciences-po.fr/hyphe and replace with it your file bin/hyphe

```bash 
wget http://jiminy.medialab.sciences-po.fr/hyphe -O /home/ramon/Documentos/hyphe/bin/hyphe
```

**Comment by uelramon** [comment]
Mr @boogheta , it works!!!!! Thank you very much!! Hyphe will help me a lot in my masters research. I want to translate some tutorials for portuguese to spread this software for researchers here in Brazil!

Again, thank you for your atention!!

**Comment by boogheta** [comment]
Thank you for your patience!
I'm closing this issue and will add a linked one to remember we need to handle differently what causes this break. Thanks for your feedback

**Comment by boogheta** [comment]
Hi @uelramon, as announced earlier on, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe now.

**Comment by uelramon** [comment]
Wow @boogheta, thank you for the update!! I'll try again, Hyphe is a very powerfull tool for my research.
