### ISSUE TITLE
Questions about the crawler of Hyphe.

### ISSUE THREAD

**Issue by uelramon** [medialab/hyphe#179]
Hello again Mr. @boogheta #,

I've been using Hyphe to crawl and built the network from a set of Facebook pages, and for curiosity when I did compare the results of crawler process with the Netvizz the result is different. Netvizz brings me a different network than Hyphe, Hyphe find's a small number of pages.

There are similar crawler in this two softwares?

**Comment by boogheta** [comment]
Hi,

These are two very different softwares. Netvizz used Facebook's API to let you build a map of a user's connections. Hyphe is intended to make a network of multiple websites so it will return something very different.
Also, Netvizz relies on you being connected to Facebook with your individual user account and rights, whereas hyphe's crawler is on the server and not connected to a specific user, so it won't be able to read private info from specific users.
Lastly, Facebook being a full-javascript website, Hyphe is usually not perfect at exploring it. You can try and activate the use of PhantomJs in the crawler to try and bypass this by setting to True the autorestart field in your config.json then bin/hyphe restart and starting a new corpus (the setting won't apply to preexisting corpus)

**Comment by uelramon** [comment]
Thanks for helping to understand the functioning of these two tools. I will try to activate the PhantomJs as you said.

Thank you again Mr. @boogheta ...
