### ISSUE TITLE
Corpus disappeares

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#195]
Hi @boogheta,

We have again experienced the sudden disappearance of a corpus from Hyphe. This time only one corpus and with very specific knowledge on when it happened.  I therefore hoped that you would be interested in taking a look at why this bug happens; though it has become much more rare it is extremely problematic that corpuses from time to time simply disappear.

**Status:**
We are running latest github version of Hyphe on Ubuntu 14.04.5 LTS. 
We are on a Big Machine (16 cores, 120GB RAM and 4 terrabyte storage).
Running 'locate' on the server shows that a long list of files from the corpus still are there. However the project doesn't show up on the overview nor in the admin. 

**Reproduction**
The users were working on the corpus yesterday afternoon. They were then suddenly logged off the system and when they tried to reenter the project were no longer on the login screen.

**Log files:**
hyphe-memorystructure-biometrics.log when the server went down: http://pastebin.com/QVkKQ3gw
hyphe-core.log showes nothing of value :(

One of the places that we do find the corpus is in the folder 'archived' where two folders have been created exactly as the corpus disappeared. What are this folder used for? Seem that it might be possible to reproduce the corpus from these json files - can you confirm that hypothesis? 

Hope all is good at MediaLab.

Best
Tobias

**Comment by boogheta** [comment]
Hey @bornakke!

It really looks like the API received a destroy call for the corpus
(accessible with confirmation from the settings page or the restricted
admin one).
Is it maybe possible one of the students did a mistake or someone with bad
intentions screwed with them?
In any case, I'd be curious to see more of the memory-structure (it starts
cut) and core logs (destroy should normally leave some trace). You can send
them to me by e-mail if that's easier.

The archived dir keeps light backups of the state of a corpus and are
generated automatically whenever a corpus is destroyed or reset. You can't
reproduce the exact same corpus from it as the web may have changed in the
mean time, but there are ways to redefine all entities with their tags and
statuses and start required crawls from these files. I haven't got the time
yet to build an automated way to do so, but I can guide you through that
during the week via IRC.

----
Benjamin Ooghe-Tabanou
médialab - Sciences-Po
84, rue de Grenelle - 75007 Paris

2016-10-03 20:14 GMT+02:00 Tobias Bornakke <notifications@github.com>:

**Comment by boogheta** [comment]
Hey Tobias! Hope we'll see you around in the coming days while we're in Copenhagen with @jacomyma  @paulgirard  & @Yomguithereal  ! :)

**Comment by boogheta** [comment]
Hey @bornakke ! Hope we'll see you around in the coming days while we're in Copenhagen with @jacomyma @paulgirard & @Yomguithereal ! :)

**Comment by bornakke** [comment]
Hi @boogheta, I'm afraid you caught me on the worst possible time.  Less than 2 months to the final hand in of my thesis and still 3 articles and an introduction to write. But if you would send me the program for the week then I can skim it through and see if there are select events that I might allow my self to participate in. However chances are rather small :-(

**Comment by Yomguithereal** [comment]
Hi @bornakke. It would be our utmost delight that you'd come tomorrow afternoon at the Hyphe "je-ne-sais-quoi" we are organizing in the TANT-lab. There will be great volumes of beers that we intend to top thereafter by going to some truculent restaurant. See you soon.
