### ISSUE TITLE
Problème de crawling / docker 

### ISSUE THREAD

**Issue by vickytikytaco** [medialab/hyphe#197]
J'utilise depuis quelques temps la version en ligne de Hyphe et je viens de l'installer sur mon mac via docker. L'installation s'est bien passée et l'application tourne (pour info, sur 0.0.0.0:8000). Néanmoins, lorsque je lance le crawl, tous les crawls reviennent "unsuccessful".

Pour info, mon set up: 
-Docker: Version 1.12.0-a (build: 11213)
-MacBook-Pro-de-Victor:hyphe-master Victor$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES

7e3171dfc1de        hyphemaster_backend    "/bin/sh -c '/bin/bas"   14 minutes ago      Up 4 minutes        0.0.0.0:6978->6978/tcp   hyphemaster_backend_1

a06ecf53ccad        hyphemaster_crawler    "/usr/bin/scrapyd"       14 minutes ago      Up 4 minutes        6800/tcp                 hyphemaster_crawler_1

2ec74908443f        hyphemaster_frontend   "/app/node_modules/.b"   14 minutes ago      Up 4 minutes        0.0.0.0:8000->8000/tcp   hyphemaster_frontend_1

b631d4a7deae        mongo:3.0              "/entrypoint.sh mongo"   14 minutes ago      Up 4 minutes        27017/tcp                hyphemaster_mongo_1

-Tout est normal sur 0.0.0.0:8000. 
-J'ai des erreurs sur 0.0.0.0:6978, cfr ci-dessous.

Avez-vous une idée ? Est-ce que je fais quelque chose de mal ? Je ne suis pas expert dans le domaine, mais souhaite réellement utiliser hyphe (les résultats que j'obtiens rien qu'avec la version démo sont très encourageants). 

web.Server Traceback (most recent call last):
exceptions.ValueError: No JSON object could be decoded
/opt/virtualenvs/hyphe/lib/python2.7/site-packages/twisted/web/server.py:190 in process
189                    self._encoder = encoder
190            self.render(resrc)
191        except:
/opt/virtualenvs/hyphe/lib/python2.7/site-packages/twisted/web/server.py:241 in render
240        try:
241            body = resrc.render(self)
242        except UnsupportedMethod as e:
/app/hyphe_backend/lib/jsonrpc_custom.py:48 in render
47        self.is_jsonp = True if self.callback else False
48        parsed = jsonrpclib.loads(content)
49        functionPath = parsed.get("method")
/opt/virtualenvs/hyphe/lib/python2.7/site-packages/txjsonrpc/jsonrpclib.py:88 in loads
87 def loads(string, *_kws):
88    unmarshalled = json.loads(string, *_kws)
89    # XXX there's going to need to be some version-conditional code here...
/usr/local/lib/python2.7/json/__init__.py:339 in loads
338            parse_constant is None and object_pairs_hook is None and not kw):
339        return _default_decoder.decode(s)
340    if cls is None:
/usr/local/lib/python2.7/json/decoder.py:364 in decode
363        """
364        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
365        end = _w(s, end).end()
/usr/local/lib/python2.7/json/decoder.py:382 in raw_decode
381        except StopIteration:
382            raise ValueError("No JSON object could be decoded")
383        return obj, end

**Comment by boogheta** [comment]
Bonjour,

L'installation via docker documentée est assez ancienne et était avant tout une expérimentation.
@jri a travaillé à rendre cette installation plus sûre et fonctionnelle ce qui devrait regler les problèmes subsistants avec la version existante, cela devrait être mis en place d'ici la fin de l'année.

**Comment by boogheta** [comment]
Bonjour,

L'installation via docker documentée est assez ancienne et était avant tout une expérimentation.
@jri-sp  a travaillé à rendre cette installation plus sûre et fonctionnelle ce qui devrait regler les problèmes subsistants avec la version existante, cela devrait être mis en place d'ici la fin de l'année.

**Comment by vickytikytaco** [comment]
Chouette, merci pour votre réponse. Impatient de pouvoir tester ça sur ma "bête machine". 
N'hésitez pas à m'envoyer un message sur mon adresse institutionnelle vwiard[at]ulb.ac.be quand c'est fait si vous voulez un feedback de ma part. 

Bien à vous, 
Victor

**Comment by boogheta** [comment]
I'm closing this for now, will inform back when new install version is ready

**Comment by boogheta** [comment]
Bonjour @vickytikytaco , comme annoncé plus tôt, nous avons finalement publié une nouvelle version avec une méthode d'installation plus générique qui devrait désormais vous permettre d'installer Hyphe beaucoup plus simplement.
