### ISSUE TITLE
depth path configuration

### ISSUE THREAD

**Issue by updiversity** [medialab/hyphe#199]
Hi,

I read in the wiki that the maximum default depth of paths from a LRU is fixed to 8. I'd like to limit this to a lower value, like 5.

I'd like to know where I can change this value.
Thanks

**Comment by boogheta** [comment]
Hi,
Not sure what you mean exactly by "default depth of path from a LRU" and this number of 8 does not ring any bell, can you point out where you read this exactly? (the wiki is not completely up to date regarding some parts)

**Comment by updiversity** [comment]
I found the info here : 

https://github.com/medialab/hyphe/wiki/Reverse-URLs 

precisely, in that paragraph : 

"
p - path. The path is all that is contains between the host and last slashes. It corresponds to subdirectories. Each subdirectory is extract and append to the reverse host. In the web, path can be as long as one wants to but it seems irrelevant for HCI to go too deep as it generally reveal a too complex or lazy web structure. Therefore, the max depth of path is arbitrarily set to 8 which is relevant to consider the vast majority of web sites.
"

**Comment by boogheta** [comment]
Yeah this page is completely out of date, not much that is said there is real :/

Basically the possible limit you might encounter of such sort is the precisionLimit in the global config.json (cf https://github.com/medialab/hyphe/blob/master/doc/config.md )

It defines the granularity up to which individual links between webpages are kept as a number of extra LRU pieces after the LRUprefix of a webentity. 2 can already be quite CPU/ram demanding, be careful not to set it up too high.

**Comment by updiversity** [comment]
Thanks for the quick reply !
