### ISSUE TITLE
mongodb run out of memory

### ISSUE THREAD

**Issue by updiversity** [medialab/hyphe#201]
hi,

it looks like by simply crawling one web entity, but with several thousands of pages, makes my mongodb crash.

this is the mongodb log trace

----- BEGIN BACKTRACE -----
{"backtrace":[{"b":"400000","o":"F24CD2","s":"_ZN5mongo15printStackTraceERSo"},{"b":"400000","o":"F24729","s":"_ZN5mongo29reportOutOfMemoryErrorAndExitEv"},{"b":"400000","o":"EAA4F1","s":"_ZN5mongo11mongoMallocEm"},{"b":"400000","o":"5BAB1B","s":"_ZN5mongo11_BufBuilderINS_16TrivialAllocatorEEC1Ei"},{"b":"400000","o":"740C89","s":"_ZN5mongo15DistinctCommand3runEPNS_16OperationContextERKSsRNS_7BSONObjEiRSsRNS_14BSONObjBuilderE"},{"b":"400000","o":"7CB223","s":"_ZN5mongo7Command3runEPNS_16OperationContextERKNS_3rpc16RequestInterfaceEPNS3_21ReplyBuilderInterfaceE"},{"b":"400000","o":"7CC0B4","s":"_ZN5mongo7Command11execCommandEPNS_16OperationContextEPS0_RKNS_3rpc16RequestInterfaceEPNS4_21ReplyBuilderInterfaceE"},{"b":"400000","o":"727750","s":"_ZN5mongo11runCommandsEPNS_16OperationContextERKNS_3rpc16RequestInterfaceEPNS2_21ReplyBuilderInterfaceE"},{"b":"400000","o":"8D70C5"},{"b":"400000","o":"8D9956","s":"_ZN5mongo16assembleResponseEPNS_16OperationContextERNS_7MessageERNS_10DbResponseERKNS_11HostAndPortE"},{"b":"400000","o":"5BBF4C","s":"_ZN5mongo16MyMessageHandler7processERNS_7MessageEPNS_21AbstractMessagingPortE"},{"b":"400000","o":"ED1495","s":"_ZN5mongo17PortMessageServer17handleIncomingMsgEPv"},{"b":"7F1347EE1000","o":"8182"},{"b":"7F1347B1B000","o":"FB00D","s":"clone"}],"processInfo":{ "mongodbVersion" : "3.2.10", "gitVersion" : "79d9b3ab5ce20f51c272b4411202710a082d0317", "compiledModules" : [], "uname" : { "sysname" : "Linux", "release" : "3.13.0-45-generic", "version" : "#74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015", "machine" : "x86_64" }, "somap" : [ { "elfType" : 2, "b" : "400000", "buildId" : "3AD3E3BF1587995C83A2A43D6B28C65A89635064" }, { "b" : "7FFFB2C0D000", "elfType" : 3, "buildId" : "9D77366C6409A9EA266179080FA7C779EEA8A958" }, { "b" : "7F1348E03000", "path" : "/lib/x86_64-linux-gnu/libssl.so.1.0.0", "elfType" : 3, "buildId" : "15A6A69B862FAC0AA589921DB1B0DF8A673FEC81" }, { "b" : "7F1348A27000", "path" : "/lib/x86_64-linux-gnu/libcrypto.so.1.0.0", "elfType" : 3, "buildId" : "607C4A6F3428B6F065D55691AFDC4E343786A8A5" }, { "b" : "7F134881F000", "path" : "/lib/x86_64-linux-gnu/librt.so.1", "elfType" : 3, "buildId" : "92FCF41EFE012D6186E31A59AD05BDBB487769AB" }, { "b" : "7F134861B000", "path" : "/lib/x86_64-linux-gnu/libdl.so.2", "elfType" : 3, "buildId" : "C1AE4CB7195D337A77A3C689051DABAA3980CA0C" }, { "b" : "7F1348315000", "path" : "/lib/x86_64-linux-gnu/libm.so.6", "elfType" : 3, "buildId" : "1D76B71E905CB867B27CEF230FCB20F01A3178F5" }, { "b" : "7F13480FF000", "path" : "/lib/x86_64-linux-gnu/libgcc_s.so.1", "elfType" : 3, "buildId" : "8D0AA71411580EE6C08809695C3984769F25725B" }, { "b" : "7F1347EE1000", "path" : "/lib/x86_64-linux-gnu/libpthread.so.0", "elfType" : 3, "buildId" : "9318E8AF0BFBE444731BB0461202EF57F7C39542" }, { "b" : "7F1347B1B000", "path" : "/lib/x86_64-linux-gnu/libc.so.6", "elfType" : 3, "buildId" : "882AD7AAD54790E2FA6EF64CA2E6188F06BF9207" }, { "b" : "7F1349062000", "path" : "/lib64/ld-linux-x86-64.so.2", "elfType" : 3, "buildId" : "9F00581AB3C73E3AEA35995A0C50D24D59A01D47" } ] }}
 mongod(_ZN5mongo15printStackTraceERSo+0x32) [0x1324cd2]
 mongod(_ZN5mongo29reportOutOfMemoryErrorAndExitEv+0x79) [0x1324729]
 mongod(_ZN5mongo11mongoMallocEm+0x21) [0x12aa4f1]
 mongod(_ZN5mongo11_BufBuilderINS_16TrivialAllocatorEEC1Ei+0x1B) [0x9bab1b]
 mongod(_ZN5mongo15DistinctCommand3runEPNS_16OperationContextERKSsRNS_7BSONObjEiRSsRNS_14BSONObjBuilderE+0x1A9) [0xb40c89]
 mongod(_ZN5mongo7Command3runEPNS_16OperationContextERKNS_3rpc16RequestInterfaceEPNS3_21ReplyBuilderInterfaceE+0x473) [0xbcb223]
 mongod(_ZN5mongo7Command11execCommandEPNS_16OperationContextEPS0_RKNS_3rpc16RequestInterfaceEPNS4_21ReplyBuilderInterfaceE+0x404) [0xbcc0b4]
 mongod(_ZN5mongo11runCommandsEPNS_16OperationContextERKNS_3rpc16RequestInterfaceEPNS2_21ReplyBuilderInterfaceE+0x1F0) [0xb27750]
 mongod(+0x8D70C5) [0xcd70c5]
 mongod(_ZN5mongo16assembleResponseEPNS_16OperationContextERNS_7MessageERNS_10DbResponseERKNS_11HostAndPortE+0x696) [0xcd9956]
 mongod(_ZN5mongo16MyMessageHandler7processERNS_7MessageEPNS_21AbstractMessagingPortE+0xEC) [0x9bbf4c]
 mongod(_ZN5mongo17PortMessageServer17handleIncomingMsgEPv+0x325) [0x12d1495]
 libpthread.so.0(+0x8182) [0x7f1347ee9182]
 libc.so.6(clone+0x6D) [0x7f1347c1600d]
-----  END BACKTRACE  -----

and this is the hyphe log

2016-11-08T01:21:57+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:
2016-11-08T01:21:57+0000 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	Failure: pymongo.errors.AutoReconnect: TxMongo lost connection to MongoDB.
	
2016-11-08T01:21:57+0000 [MongoProtocol,client] Unhandled Error
	Traceback (most recent call last):
	Failure: pymongo.errors.AutoReconnect: TxMongo lost connection to MongoDB.

What would you recommend to avoid this problem ? for example, should I add swap to my system ?

**Comment by boogheta** [comment]
Hi,
I must admit I really don't have much ideas there...
Have you tried your local MongoDB in another context?
It looks to me more like something you should investigate with MongoDB's help.
