### ISSUE TITLE
L'indexation ne démarre pas pendant les crawl

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#214]
![image](https://user-images.githubusercontent.com/193478/28819765-8ff0a840-76af-11e7-9def-12747b58d449.png)

Hypothèses des conditions dans lesquelles ce bug apparaît : 
Quand un corpus est éteint puis rallumé ?

**Comment by paulgirard** [comment]
restarting Hyphe restarted indexation.
I keep it open and make some more tests

**Comment by paulgirard** [comment]
Haven't work on this. Let it open for record.

**Comment by boogheta** [comment]
Can't get a hand on it, maybe Hyphe had crashed? Have you looked at the logs then?

**Comment by boogheta** [comment]
looks like it was coming from cases following a reset, should be fixed now
