### ISSUE TITLE
[front] [tags] Init autocomplete on click (not only on type)

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#236]
A user has no desire to write in order to pick an existing tag

**Comment by paulgirard** [comment]
mmmm this fix does not seem to work at least in the version I use fro Polarisation ?

What I was about to write in a new issue was : we should able to see tag proposition when clicking in the tag value and not having to start typing.

**Comment by boogheta** [comment]
It looks like it only works within the TAGS page, not in the single webentity's one indeed! it looks like it does not use the same component
