### ISSUE TITLE
Docker missing build path

### ISSUE THREAD

**Issue by dentoir** [medialab/hyphe#240]
Hi,

When trying to build a Docker image via docker-composer, the docker-compose.yml file (branch: master) seems to reference a non-existing path.

After executing `docker-compose up`
the following error message is displayed:

`build path /home/scrapy/hyphe/memory_structure either does not exist or is not accessible.`

Is this a known issue, and/or is there a fix for this?

Best,

Emile

**Comment by boogheta** [comment]
Hi @dentoir,
We are currently working in a huge refactoring of the code base, including soon a proper docker install, but currently the docker files are no more in sync with the codebase indeed
I can only advise you to either wait for a couple months before we're completely done, or try to adapt yourself the docker files (you can get hints from the "docker-material" branch, which is unfotunately not up to date but very close to what needs to change for docker)
ping fyi @jri-sp

**Comment by ErikBorra** [comment]
Darn, finally we have the time to install Hyphe, and now we have problems with Docker, the old Scrapy (which results in the same problem as issue #209), and scrapy's apt which is down :p I guess we'll have to wait until you are done refactoring. Best of luck with it!

**Comment by jacomyma** [comment]
The Docker install is for soon but in the meanwhile the way to go is to do a fully manual install. The documentation is not up to date though. Contact us if you are in a hurry...

**Comment by boogheta** [comment]
@ErikBorra Furthermore, apparently scrapy'apt down is gonna be a permanent thing... https://github.com/scrapy/scrapyd/issues/25
This means that for manual install, scrapyd will no longer be used as a system daemon service but will rather have to be started "manually" separately by the sysadmin of the machine (which is quite easy to do, but not best for maintenance). 
So I believe the docker install will now become the best proper way of installing as it will take care of this itself.

**Comment by boogheta** [comment]
@ErikBorra Furthermore, apparently scrapy'apt down is gonna be a permanent thing... scrapy/scrapyd#209
This means that for manual install, scrapyd will no longer be used as a system daemon service but will rather have to be started "manually" separately by the sysadmin of the machine (which is quite easy to do, but not best for maintenance).
So I believe the docker install will now become the best proper way of installing as it will take care of this itself.

**Comment by Digenis** [comment]
@ErikBorra,
There are no instructions on how to do a manual system install of scrapyd
but reading the install script and related info for debian can help.
I just opened https://github.com/scrapy/scrapyd/issues/258 for this.
Any feedback there is welcome.

**Comment by boogheta** [comment]
Hey @dentoir @ErikBorra we will release properly in 10 days, but overall the docker files have been updated and shouldn't move much more. We've updated the README accordingly, some more documentation still needs to be added as well as for the old installation way, but if you wanna try the docker install already, you're very welcome :)

**Comment by ErikBorra** [comment]
Thanks for the heads-up! This month we're fully packed, but we'll definitely take some time this year to properly set up Hyphe :)

**Comment by boogheta** [comment]
Hey guys, I allow myself to close this as it was really related to an older version irrelevant now. Don't hesitate and reopen a new issue if you have one when you'll try with the latest release!
