### ISSUE TITLE
Warn when using Edge ?

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#246]
@jacomyma: it looks like even Edge has issues with Hyphe, maybe we should have the same kind of warnign as for IE

**Comment by Yomguithereal** [comment]
@boogheta: can we pinpoint the issues? Edge is relatively modern.

**Comment by jacomyma** [comment]
A warning is definitely an option but insofar as Edge is HTML5, Hyphe is supposed to work. It is necessary to identify where the problem is first, in order to be sure that it does not come from a mistake on my side.

**Comment by boogheta** [comment]
sounds better indeed if it can simply work :)

**Comment by jri-sp** [comment]
I got an `Access-Control-Allow-Origin` issue with Hyphe and Microsoft Edge.
Hyphe (commit https://github.com/medialab/hyphe/commit/1a5d608d5f0f5a17943836094ba7bab07821e86a) was built and started with Docker for windows (17.03.0-ce-win1) 
I'm using `http://localhost`

Screenshot:
<img width="1920" alt="hyphe_edge_cors" src="https://user-images.githubusercontent.com/5879903/34776132-08d57e12-f616-11e7-8908-d3c4570ac210.png">
