### ISSUE TITLE
Hyphe changes ":" in to-be-crawled URLs in "%3A"

### ISSUE THREAD

**Issue by Guillaume-Levrier** [medialab/hyphe#248]
Here is what I get in my web entity:
> **ID**
> 4
> 
> **Name**
> ##rnhub.com /.../_page:4_
> 
> **Status**
> IN
> 
> **Home page**
>  link http://##rnhub.com/details/news/_page%3A4_

This obviously goes to a 404, making the web entity uncrawlable. Any solution?

**Comment by boogheta** [comment]
example url: https://www.altmetric.com/details/23373063/news/page:1
notes for later:
- try to add ':' in safechars line 260 of hyphe_backend/lib/urllru.py
- handle also in front ?

**Comment by Guillaume-Levrier** [comment]
Problem solved, thx.

**Comment by boogheta** [comment]
let's keep it open so that we can remember to fix it for everyone plz :p
