### ISSUE TITLE
[NETWORK] Add a search in the network view?

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe#255]
Good idea?

Leftover todolist:
- [x] only display the BottomLeft box when a WE is selected
- [x] remove the button when the BottomLeft box is closed and no WE is selected
- [x] remove the search input from the BottomLeft box
- [x] use the name of the selected WE as title in the top bar of the BottomLeft box
- [x] make the search input in the sidebar full width
- [x] add a cross on the right of the search input to deselect the WE
- [x] make the lower margin of the search input smaller ?
- [x] "raise" the BottomLeft Box
- [x] allow the box to be a bit larger (but not too much, like with a min-width and max-width instead of a width) when the WE name is a bit longer 
<s>- [ ] then rethink logic cf https://github.com/medialab/hyphe/commit/9a7d61be3618592bf54583e95b63c72f0dfa8903#commitcomment-35564406</s> cf #357

**Comment by boogheta** [comment]
:+1:

**Comment by boogheta** [comment]
In the NETWORK page, add a small SEARCH section below FILTERING with a text input with autocompletion on WebEntities names and highlight the corresponding node on selection (color? size? big label?) as well as the links from and to it in different colors
