### ISSUE TITLE
GEXF export: remove unnecessary columns

### ISSUE THREAD

**Issue by jacomyma** [medialab/hyphe#258]
Some node attributes are necessary to the UI (like the tags object) but useless for the GEXF export (tags are also rewritten as normal attributes). It would be nice to remove these attributes from the export. It could be a Graphology feature.

**Comment by boogheta** [comment]
It looks to me like the two fields which could be removed from GEXF are tags and prefixes (or they should be given as urls instead if we want to keep them, but I feel like homepage is enough documentation of this aspect)

**Comment by boogheta** [comment]
Looks to me like we should remove tags and prefixes
And yes, I agree that looking at how it is plugged, the best solution would be for graphology's  `gexf.write` function to take as extra arguments either a list of desired keys or better in our case a list of undesired ones.
cc @Yomguithereal

**Comment by Yomguithereal** [comment]
The gexf library already packs a reducing option so you can do this kind of thing. I’ll check this when I return.

**Comment by boogheta** [comment]
If you can point me to the corresponding doc or code, I can try to use it tomorrow

**Comment by Yomguithereal** [comment]
Look at formatNode and formatEdge here: https://github.com/graphology/graphology-gexf/blob/master/README.md#browser-parser

Maybe you’ll need to upgrade the lib’s dep.
