### ISSUE TITLE
Adding a tag to some specific categories starts infinite add/remove loop

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#276]
Dans l'onglet tags de la page d'une webentité
- créer une categorie "language"
- puis créer un tag
=> boucle infinie de add/remove

**Comment by boogheta** [comment]
It appears it only happens with the category "language" in fact ! o_O

**Comment by jacomyma** [comment]
The server answers: "ERROR while updating WebEntity : found language override field in document with non-string type"

**Comment by boogheta** [comment]
As identified by @Yomguithereal, it probably come from the textIndex line 117 of hyphe_backend/lib/mongo.py, it should take an extra_argument such as "{ language_override: "HYPHE_MONGODB_LANGUAGE_INDEX_FIELD_NAME" }"
cf https://docs.mongodb.com/manual/tutorial/specify-language-for-text-index/
