### ISSUE TITLE
Update user agents list

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#282]
It hasn't changed since 2013 : https://github.com/medialab/hyphe/commit/9ec157f21ef87b9a5faf0dfc897a6062ca6e34c3#diff-53c6036cc138678080744d7e9acad939

Which might help facebook kick us ;)

**Comment by Yomguithereal** [comment]
@farjasju 

# Hyphe User-Agent Revamp Specs

1. Installer la lib et l'enregistrer `requirements.txt`
2. Le module user_agents.py doit maintenant exporter une fonction renvoyant un user-agent random à utiliser
3. Il doit utiliser la librairie si possible ou fallback sur une liste en local si ça ne marche pas
4. La librairie ne doit pas télécharger les infos sur le disque (lire la doc de la lib pour trouver la bonne option)
5. La liste des agents doit maintenant se trouver dans un fichier `user_agents.txt` avec un User-Agent par ligne dans le dossier `lib` à côté du fichier `tld_list.txt`.
6. Le package doit avoir un `__name__ == '__main__'` exécutant un script générant, grâce à la librairie, le fichier `user_agents.txt`.

**Comment by farjasju** [comment]
Seems to be okay (waiting for your criticisms) !

**Comment by Yomguithereal** [comment]
Can you open a Pull Request on the repo from your branch to master or dev (@boogheta knows which one)?
