### ISSUE TITLE
[NETWORK] Let one visualize links direction on the network?

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#286]
The actual click on node in the network opens the webentity page in a new tab, which is not necessarily very useful.
Ideally, we should instead open some kind of options box that would give various info/links on the webentity, but a fast and dirty improvement could be to use the click node as a way to visualize quickly the direction of the links to the clicked webentity, for instance with 3 colors, (inbound, outbound, reciprocal) and reset the links colors when clicking on the background

What do you think @paulgirard @jacomyma @Yomguithereal?

**Comment by jacomyma** [comment]
I agree with the necessity of a panel/menu/something on click on a web entity, the would lead to different options. For visualizing the direction of links, different behaviors might be implemented on the right sidebar. These options might rely on Sigma features like arrows and curved edges. I believe they are on its roadmap - am I right @Yomguithereal ?

**Comment by Yomguithereal** [comment]
<stealthily leaves this conversation>

**Comment by boogheta** [comment]
If we already have the search from #255, clicking a node on the graph could select the corresponding webentity within the input (with links on the right of the input to the webentity page and its homepage) and do the in/out links coloring
