### ISSUE TITLE
When merging a webentity into another, the resulting one has the first one's homepage

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#291]
Tags are properly merged, but homepages seem merged the other way around

**Comment by audreybaneyx** [comment]
it would be a good idea to automatically choose/modify the homepage of the Web entity under which we have gathered the others. We could exclude the URLS containing twitter, instagram or Facebook references and choose the most related URL (in and out) for the WE
The first one's homepage isn't always clean.
