### ISSUE TITLE
bug in autocomplete

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#294]
in corpus polarisation deep, the tag "portée" does not show any recommandation.
Note this is true in both hypeh web client and Hybro so it looks like a CORE bug ?

**Comment by boogheta** [comment]
might be linked to an accent thing, although I can't seem to reproduce, in the TAGS page I have a set of autocompletion values proposed when clicking in the Portée category, and in a single webentity'one as weel when typing for instance "a"

**Comment by paulgirard** [comment]
And when the accent is in a possible value ?

**Comment by paulgirard** [comment]
To be more explicite the issue can be reproduced in the polarisation deep corpus as : 
- go to a web entity
- click in Porté catégorie
- type nat
- the itnerface only proposes "national" where this tag has much more value available like nationale, régionale...
