### ISSUE TITLE
Web entities list pagination + selection

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#303]
To replicate:
Go to web entities list
search something which replies a long list of WE
select the first two (you should see the cart/action box)
then scroll enough to tigger a pagination call
try to select a few more 
=> the selection is not added to the cart.

Alternative scenario.
Don't select before scrolling to paginate.
If you select after pagination, the cart/action box does not appear at all.

Looks like the pagination call breaks the event listener of selection actions ?

**Comment by boogheta** [comment]
can't reproduce anymore, let's assume it was fixed by border effect and reopen if we encounter it again ;)
