### ISSUE TITLE
[WEBENTITY] display error message from API response when editing a WE's metadata

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#304]
In web entity, if I decide to change home page to a web page which does not match a prefix, the api replies : 
```json
[{"message": {"homepage": "WARNING: this page does not belong to this WebEntity, you should either add the corresponding prefix or merge the other WebEntity."}, "code": "fail"}]
```
The Interface correctly warn that there were an error but does not display the useful message.

The error message returned by Hyphe should be displayed in the notification bar as a feedback so that the user knows he should change his input.
Even better, inputting an outside-prefixes homepage could trigger a modal proposing to add the corresponding prefix or merge the corresponding entity if it exists the same way it does in the Crawls page when adding a new startpage

**Comment by paulgirard** [comment]
Might be true elsewhere.

**Comment by boogheta** [comment]
it used to do it, but @jacomyma didn't redo it in his refactoring of the edit WE menu :p

**Comment by boogheta** [comment]
It should be fixed by copying the API error message within the status header bar
