### ISSUE TITLE
What about nested imbricated webentities?

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe#326]
Example:

```
( ): webentity 1
{ }: webentity 2
( [com] -> [twitter] ) -> { [yomgui] } -> ( [photos] )
```

Are they a thing? Should they be a thing? This probably breaks the traph on many levels (pages would not overcome the first child webentities to find underlying pages, or would void medialab/hyphe-traph#22 optimizations, for instance).

**Comment by boogheta** [comment]
Decision CPH191021-1430 :
It should not have any impact on the traph, although, it probably breaks crawls on the nofollow rules, and should be fixed by using ural's LRUTree
