### ISSUE TITLE
The API list_corpus request returns corpuses as properties of an object

### ISSUE THREAD

**Issue by Guillaume-Levrier** [medialab/hyphe#328]
While an array would be much more practical ?
![Capture](https://user-images.githubusercontent.com/18345966/63503826-88455e80-c4d0-11e9-8204-f1b1533f105a.PNG)

**Comment by boogheta** [comment]
This is a common way of returning such elements for which one might want to directly access a corpus data by id through the map. Every language has very simple commands to return an iterable array from it like Object.keys(d) & Object.values(d) in JS or d.items(), d.keys() and d.values() in python
