### ISSUE TITLE
API documentation syntax issue

### ISSUE THREAD

**Issue by Guillaume-Levrier** [medialab/hyphe#329]
There's probably a ` missing somewhere in the

- `get_webentities:`

entry, which means that this

>  Returns for a `corpus` all existing WebEntities or only the WebEntities whose id is among `list_ids.
>  Results will be paginated with a total number of returned results of `count` and `page` the number of the desired page of results. Returns all results at once if `list_ids` is provided or `count` `_ (optional, default: `= -1 ; otherwise results will include metadata on the request including the total number of results and a `token` to be reused to collect the other pages via `get_webentities_page`.`)
>  Other possible options include:

should probably look like this :

>  Returns for a `corpus` all existing WebEntities or only the WebEntities whose id is among `list_ids.`
>  Results will be paginated with a total number of returned results of `count` and `page` the number of the desired page of results. Returns all results at once if `list_ids` is provided or `count` `_ (optional, default: `= -1 ; otherwise results will include metadata on the request including the total number of results and a `token` to be reused to collect the other pages via `get_webentities_page`.`)
>  Other possible options include:

**Comment by boogheta** [comment]
indeed, thx!
