### ISSUE TITLE
API faultString: "function get_webentities_stats not found"

### ISSUE THREAD

**Issue by Guillaume-Levrier** [medialab/hyphe#330]
I'm sending two requests : one to start the corpus and then aother one to retrieve the stats and get an idea of the WE's statuses. This is what I get:

First request - `start_corpus`
> code: "success"
> result: {ready: true, status: "ready", message: "Corpus already ready", corpus_id: "donjons-dragons-et-trotskisme"}

Second request - `get_webentities_stats`
> fault: "NoSuchFunction"
> faultCode: -32601
> faultString: "function get_webentities_stats not found"

What am I doing wrong ?

**Comment by boogheta** [comment]
`start_corpus` is in the "no namespace" list of functions, whereas `get_webentities_stats` is in the `store` one, so you should call it as store.get_webentities_stats instead

**Comment by Guillaume-Levrier** [comment]
Got it, it works now, thanks a lot!
