### ISSUE TITLE
Uncapitalize the first letter of the domain name in the WE lists (prospects / web entities)

### ISSUE THREAD

**Issue by Guillaume-Levrier** [medialab/hyphe#332]
More a quality of life issue, but the first letter of a domain name isn't usually capitalized. It feels weird for I/l (capital i and lower L) for example. Capitalizing everything could be a solution as well. A website named iied.org is displayed **Iied.org** which looks a lot like **lied.org** if you don't pay attention, but in fact it is `iied` and not `lied`. I guess you get what I mean.

**Comment by boogheta** [comment]
This was actually a design choice to capitalize the first letters of pieces of domain names to actually ease the reading for instance with Such-Domains.org.
Also the problem you encounter seems more solvable through a different font choice for instance with serif, which would also be more of a design choice to make.
@jacomyma your 2 cents on this ?

**Comment by jacomyma** [comment]
Oh, it's a design choice. See: the web entity is not necessarily, and does not have to be, a domain. Even if it often is with default settings. So Guillaume's assumption is wrong. But he is right insofar as it often looks like a domain.

Having a capitalized version is a hint at that. It is also a rule that is more consistent with editing your entities. Indeed, I think it is not obvious to most users that web entities are not necessarily domains (or subdomains). There are not so many ways we can elicit that awareness.

**Comment by Guillaume-Levrier** [comment]
Well a first point is that it doesn't really answers the question: the domain name on which the WE is to be found can be an important hint, and potentially misreading it doesn't make the process any easier.

A second is that maybe you could change the way the extension is displayed, so that it looks even less like a domain name? Putting it between brackets to keep the differenciation among WEs? Like you'd go from Iied.org to iied [org]. 

A third would be that it sounds that you kept it that way because WEs can be domains but at the same time they can be something more narrow/different so we users should be reminded of that potential difference by a capital letter somewhere. I'm only speaking for myself here, but I didn't get the hint. Maybe make a hint list ?

**Comment by boogheta** [comment]
Decision CPH191021-1430 :
Won't fix, having a capital letter at the beginning is important since they are proper names of the actors. The problem described here is rather a font problem than a format one. If it really poses a probleme in your case, you can solve if you like by applying some css change over the website with tools such as greasemonkey, or within a Hyphe fork

**Comment by Guillaume-Levrier** [comment]
Fine, I'll do my own hyphe with D3.JS heatmap previews, serif fonts and iframes. 

![DcRXqn6WsAAq-6M](https://user-images.githubusercontent.com/18345966/67213838-05cd1280-f41f-11e9-84b8-5a3731862ba9.jpg)
