### ISSUE TITLE
Automtic docker build from gitlab have wrong version names

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#339]
Whenever we release vX.Y.Z on github creating a branch with the same name, we want to deploy on DockerHub a new tag X.Y.Z for the three containers, which the gitlab automated CI pipeline properly does but to a wrong name vX-Y-Z

**Comment by boogheta** [comment]
It looks to me like changing all refs to "CI_COMMIT_REF_SLUG" into "CI_COMMIT_TAG" in  .gitlab-ci.yml should do the trick but i'll let @jri-sp confirm

**Comment by jri-sp** [comment]
It should be OK now

**Comment by boogheta** [comment]
@jri-sp I just released a new tag v.1.3.0 and it built and pushed v1.3.0 on dockerhub, but I thought what we did was gonna build 1.3.0 wasn't it the idea?

**Comment by jri-sp** [comment]
May 71d86fc be my last commit for this issue...!

**Comment by boogheta** [comment]
Seems like it it! :confetti_ball:
