### ISSUE TITLE
Web entity edit: check all pages as start pages

### ISSUE THREAD

**Issue by jacomyma** [medialab/hyphe#352]
Subject to discussion.

It's about the "edit web entity" page, where we see the list of pages. We now have a switch to make a page a start page.

A user suggested that we have a global switch to add all / remove all pages from the start pages list.

Pros:
- Useful in certain use scenarios.
- The feature is pretty common and makes sense in terms of consistency.

Cons:
- We want to prevent a problematic scenario where users check all to "gain" an additional depth instead artificially
- Removing all start pages does not make much sense

**Comment by boogheta** [comment]
Side issue: the list of pages on the right does not necessary include the startpages on the left, it might be more logical to include them as well so they can be removed from startpages from there as well as the others

**Comment by boogheta** [comment]
I'm not too worried about the problematic scenario, it might be annoying on the demo, but having a ma depth of 1 the user would still need to go back and forth so I don't think it would be too much of an issue.

But I agree the "remove all" button would be a bit weird. Although I feel like it is necessary for when someone used the selectAll by mistake and it is not too critical.

So I feel like we should do it, and it shouldn't be too complex (but I need to add API routes to allow adding/removing multiple startpages at once before or it would be overkill calling the API so many times)

@jacomyma I feel like the good place for such buttons would be within the "Startpages" tab at the top or the bottom, what do you think?

**Comment by jacomyma** [comment]
I agree with your analysis. I think the logical place is on top of the list; that is where I would search for this feature (see image below).

![button place](https://user-images.githubusercontent.com/158525/68964696-4fb8d680-07da-11ea-9005-40e16d3ec7e4.png)

**Comment by jacomyma** [comment]
Additional remark: the buttons may take place, as you suggest, in the "start pages" tab, if we wish to semi-hide / disincentivize them. Honestly, I am not against it.

**Comment by boogheta** [comment]
Yep, naturally I would do on top as you suggest, but I feel like needing two buttons with quite explicit text and considering the desire to avoid abuse of the feature, semi-hiding it within the startpages tab seems a good option :)

**Comment by boogheta** [comment]
(and I reintroduced already on top the search through pages feature (which triggers the collection of all pages not loaded yet when used) so that would be a bit heavy there)
