### ISSUE TITLE
Warning when leaving prospect

### ISSUE THREAD

**Issue by jacomyma** [medialab/hyphe#361]
Observed on the Demo instance.
When we prospect and leave the page, there is a warning about IN pages that are not crawled, which is a nice protection. However, the warning is also present when we click on the "crawl" button, where it does not make much sense (since we precisely leave the page to do the crawling).

**Comment by boogheta** [comment]
Yeah it's already been noticed and fixed but the commit is not in prod yet, coming soon! :)
