### ISSUE TITLE
[IMPORT URLS] Simulate Webentity creation rule should take the matching rule with the longest prefix

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#363]
In some cases it does the opposite, for instance when we have
```
- facebook.com: path-1
- facebook.com/pages: path-2
- facebook.com/groups: path-2
- facebook.com/people: path-2
```

and we try to import the following batch
```
https://www.facebook.com/dude
https://www.facebook.com/dude/
https://www.facebook.com/people/dude
https://www.facebook.com/people/dude
https://www.facebook.com/groups/dude
https://www.facebook.com/groups/dude/
https://www.facebook.com/pages/dude
https://www.facebook.com/pages/dude/
https://www.facebook.com/post/dude
https://www.facebook.com/post/dude/
```

It should propose all WEs completely to the right except for the last 2 but it only proposes path-1 for all

This may come from calls to `get_potential_prefix` in the traph? cc @Yomguithereal

**Comment by Yomguithereal** [comment]
The traph is geared to returning the longest prefix but maybe there is something not working as intended.

**Comment by boogheta** [comment]
Well in fact, the traph wasn't the culprit, it was due to www variations of default creation rules not being automatically created
