### ISSUE TITLE
Requirements.txt has a dependency conflict with tld and ural

### ISSUE THREAD

**Issue by stijn-uva** [medialab/hyphe#375]
While installing Hyphe's dependencies with pip from the current version:

`ERROR: ural 0.19.0 has requirement tld>=0.11.8, but you'll have tld 0.9.7 which is incompatible.`

These versions are indeed required by requirements.txt. Changing to `tld>=0.9.7` seems to fix this (though I haven't checked extensively whether this breaks other things).

**Comment by Yomguithereal** [comment]
The tld libs has made a lot of weird updates lately. I guess I need to lock ural deps once more :)
