### ISSUE TITLE
mongo < 3.2 (hyphe default to 2.8) fails on debian > 9

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#377]
Because of outdated kernel calls mongo < 3.2 can't be run even through docker on recent kernels.
We couldn't make it run on debian 10.

Without taking time to a deep testing session, upgrading to mongo 3.2 looks like working for hyphe on a debian 10 ecosystem.

Upgrading to mongo 3.2 is nonetheless a breaking change because of filesystem change.
To be considered in next major release.

**Comment by arnaudmolo** [comment]
+1, I may had the same problem on my own debian 10 server

**Comment by Chatoranga** [comment]
I had the same probleme, so I changed mongo:3.0 to mongo:3.2 in the docker-compose file but I still have the same error message... What should I do ?

**Comment by boogheta** [comment]
Hi @Chatoranga, can you open a new issue with more details with the problems you're encountering, logs and such?
