### ISSUE TITLE
Updating Hyphe makes Corpus inaccessible

### ISSUE THREAD

**Issue by ralphverwegen** [medialab/hyphe#381]
Hey,

I used the instructions on Github to update Hyphe after it had stopped functioning. Can anyone tell me if I can still access my old corpus and how? This would be greatly appreciated. My research depends on it. 

Thank you

**Comment by boogheta** [comment]
I guess you are using Docker and followed [this line](https://github.com/medialab/hyphe#7-update-to-future-versions)?
Do you know which version you used to have before, what TAG version is set in your .env file and/or when it was?

**Comment by ralphverwegen** [comment]
Thnx Boogheta. Yes, I am using docker and I followed that line.
No, unfortunately I don't know which version I had. I installed docker and Hyphe about 5 months ago.
How would I find the TAG version in my .env file?

The updates were made today

**Comment by ralphverwegen** [comment]
Oh, and thank you so much for trying to help me

**Comment by ralphverwegen** [comment]
I think it says Tag=Prod

**Comment by ralphverwegen** [comment]
Hey Boogheta, 

Firstly, thank you so much for helping me, it means a lot. Do you have a guide or some instructions on how to access the content of the folders listed in the Mountpoint?

Thank you

**Comment by boogheta** [comment]
Hi, sorry but I gave you the instructions I would use already. Apparently your machine has some weird setup, so you will need to figure out this part.
Something along noting the path values for each directory, logging as root, then doing ls and du on these paths.

**Comment by ralphverwegen** [comment]
Ok, thnx. I'll keep on trying. 

My machine runs on windows, not Linux, if that changes anything.

**Comment by boogheta** [comment]
Ha that might explain things, unfortunately I don't had any experience with Windows in the last 15 years so I won't be able to help much on this part, but Google and StackOverflow will probably be helpful, sorry :/
