### ISSUE TITLE
Adding www.google.com/url to redirection list not working?

### ISSUE THREAD

**Issue by ladelentes** [medialab/hyphe#388]
When I crawl a website built with Google Sites, the only “discovered” entity is [google.com], despite several links to external websites actually present.

Google Sites changes all hyperlinks from [href=“http://somesite”] to [href=“http://www.google.com/url?q=http://somesite”]. 

The **Redirection Domain** ([www.google.com/url]) is not included in the current Configuration file. 

I added both [www.google.com/url] and [google.com/url] to the list of **Redirection Domains** (I tried manually in the config file and through the web interface on localhost), but it hasn’t made a difference. 

Even after adding this new redirection domain and restarting Hyphe, the real targets of the masked hyperlinks are not added as Discovered Web Entities.

Is this a bug? (please fix if possible)
Or does something else need to happen for a new **Redirection Domain** to be recognised? (please add to documentation if possible)

Here's the example website http://feminicidiouruguay.net

Thank you for your help!

**Comment by boogheta** [comment]
Hi and thanks for the report,
It seems like Google Sites redirections are javascript redirections and not server ones which makes it a lot more complex to handle.
Fixing it would require to parse the html content in the response to identify such javascript redirection and handle them. Thuis should be done somewhere in here: https://github.com/medialab/hyphe/blob/master/hyphe_backend/crawler/hcicrawler/resolver.py#L30
The team is unfortunately quite busy with other tasks currently, but this is an issue which should indeed be adressed!

**Comment by ladelentes** [comment]
Thanks for the response! I'll see if I can find a workaround.
