### ISSUE TITLE
htpasswd cannot work in config-frontend.env because nginx conf is overwritten

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe#390]
In the Docker entrypoint of the frontend, the nginx config is sed'ed to take the htpasswd into account [here](https://github.com/medialab/hyphe/blob/db4ee9cc053c25be5ae7d982862f3c11a1f3a604/hyphe_frontend/docker-entrypoint.sh#L23), but the conf is then overwritten [here](https://github.com/medialab/hyphe/blob/db4ee9cc053c25be5ae7d982862f3c11a1f3a604/hyphe_frontend/docker-entrypoint.sh#L27) making the whole thing moot :)

**Comment by boogheta** [comment]
LOL bien vu :)

**Comment by boogheta** [comment]
Simplement remonter la ligne 27 en ligne 20 me semble rêgler le problème non?

**Comment by Yomguithereal** [comment]
Il me semble, à moins que le sed tape sur des patterns qui ne sont plus présent dans le fichier après envsubst.
