### ISSUE TITLE
Fix specific WECRs not working after reset (although saved)

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#392]
For instance Twitter accounts do not seem to trigger new WEs

**Comment by boogheta** [comment]
It seems to come from the "clear" function in the traph which removes everything while we do not reinstantiate a new traph with the WECRs, @Yomguithereal will add an option to clear to fix this

**Comment by Yomguithereal** [comment]
Should be available on v1.3.0 of the traph now.

**Comment by boogheta** [comment]
\o/
