### ISSUE TITLE
in:install  ERROR: Cannot connect to mongoDB [SOLVED]

### ISSUE THREAD

**Issue by gbousqu** [medialab/hyphe#394]
Hello,
I'm new to docker and github and tried to install hyphe on a windows 10 pc first. 
I installed docker and github and then follow the required steps to install hyphe.
$ docker-compose pull > Ok.
But $docker-compose up  > failed : 
![image](https://user-images.githubusercontent.com/12803225/104445791-d9f4fa00-5599-11eb-9bd0-8e181c696024.png)
If I don't succeed I'll try on my Ubuntu 18.04 server. But first I'd like to understand.
Thank you.

**Comment by boogheta** [comment]
Hello,
It seems like MongoDB does not want to start within its Docker container for some reason which does not appear in your logs.
It might be due to an evolution in the underlying containers, which we actually changed in the latest release I just published? So may I ask you to retry after pulling the containers again?

**Comment by gbousqu** [comment]
thank you for the quick answer. I'll retry it tomorrow, from the beginning.

**Comment by gbousqu** [comment]
i removed the docker container hyphes, deleted the hyphe directory, then reinstall from the beginning :  git clone (...) , docker-composer pull (ok), docker-compose up and got ... a different error log : 
![image](https://user-images.githubusercontent.com/12803225/104509867-95457f00-55ea-11eb-890e-f43c29f85635.png)
the config.json doesn't exits in conf directory, there is just the config.json.example file.

**Comment by boogheta** [comment]
Nope it's actually the same log, with just minor differences.
So basically the mongodb service does not want to start on your machine. It may be related to the kernel used by Windows to emulate linux containers which would be too recent (like in issue #377
Could you try to edit docker-compose.yml and change all the way at the end the line "mongo:3.0" into "mongo:3.2" and retry?

**Comment by ralphverwegen** [comment]
worked for me. At first it wouldn't recognize the new file as a .yml file, but after copying and editing the file name a couple of times, everything took off. Thank you @boogheta

**Comment by gbousqu** [comment]
Il just tried your solution @boogheta  and it works like a charm
Thank you very much.

**Comment by boogheta** [comment]
Cool, thanks for both of your feedbacks, this confirms we shall migrate mongo version for future releases as discussed in #377, although this will break existing corpuses, so I guess this will for version 2.0.
