### ISSUE TITLE
Need xCode on Mac

### ISSUE THREAD

**Issue by mere13** [medialab/hyphe#399]
First, thank you for developing such a fantastic tool. Just a minor suggestion about the installation instructions. In addition to Docker (on Mac), I also needed xCode. In retrospect, this is obvious but it took me awhile to remember I'd wiped my laptop to clean state and that's what was causing my install error. Might be worth putting a note in the instructions.

**Comment by boogheta** [comment]
Very good suggestion indeed, thanks for your report, will add it to the Readme right away!
