### ISSUE TITLE
 ERROR: Cannot connect to mongoDB, please check your server and the configuration in config/config.json

### ISSUE THREAD

**Issue by Chatoranga** [medialab/hyphe#400]
![docker hyphe](https://user-images.githubusercontent.com/79143400/108057653-30e76680-7053-11eb-88a9-bce5a49a594c.PNG)
Hello, I'm trying to install Hyphe. And this error message appears when I do the docker-compose up command. I read that the problem could be that I am doing this with windows. I tried to change the docker-compose file, with mongo:3.2 instead of mongo:3.0, but I still have the same error message : ERROR: Cannot connect to mongoDB, please check your server and the configuration in config/config.json

**Comment by boogheta** [comment]
Hi and thanks for the detailed log.
It looks like MongoDB has issues with data from the previous version maybe, can you try to wipe out clean your install by removing existing containers, images and volumes related to your hyphe install? (you can find commands for this here https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes )

**Comment by Chatoranga** [comment]
Thank you for your answer ! I tried and it did not work....
![docker hyphe 2](https://user-images.githubusercontent.com/79143400/108060388-17e0b480-7057-11eb-918d-b85ec80e1661.PNG)

**Comment by boogheta** [comment]
I think it's still finding some mongo files in what he considers to be /data/db, which should be either in your hyphe directory under a `mongo-data` directory, either somewhere else if you set up the DATA_PATH variable in the `.env` file (in which case it should be under DATAPATH/mongo-data). can you check whether these exist and remove all files within before retrying to start Hyphe?

**Comment by Chatoranga** [comment]
I am not sure to understand what I am supposed to do. I'm not very familiar with Docker and all those things... What kind of files should I remove ? I don't have any file named "mongo-data" in my hyphe directory.

**Comment by boogheta** [comment]
And I am myself not very familiar with Windows unfortunately... For what I understand you need to remove the volume in which docker stored some mongo data already.
You should be able to do so using things like this:
```docker volume ls```
This should list some volumes, including one or more named something like hyphe_mongo-data, note their exacts names, then run the following for each of them, by replacing NAME with the volume name:
```
docker volume rm NAME
```

**Comment by Chatoranga** [comment]
Thank you so much ! I got to deal with another bug (the fronted port was already allocated), but it now seems to work !

**Comment by boogheta** [comment]
Great! I will close this issue then, but feel free to reopen if you encounter more issues!
