### ISSUE TITLE
Edge identification

### ISSUE THREAD

**Issue by ralphverwegen** [medialab/hyphe#415]
I'm interested in identifying the specific hyperlink(s) that constitute certain edges. In other words, I want to know exactly what parts of a website were linked to. It this possible with hyphe?

Thank you for your time

**Comment by boogheta** [comment]
Hello @ralphverwegen,
This information is stored in details by hyphe but is not easily retrievable as such so far.
From the frontend web interface you cannot, but you can access via the backend API the detailed links between pages for each webentity using the route store.paginate_webentity_pagelinks_network as documented here: https://github.com/medialab/hyphe/blob/master/doc/api.md#pages-links-and-networks

**Comment by ralphverwegen** [comment]
Thank you @boogheta 

I appreciate your time.
