### ISSUE TITLE
Problem w. saving tags

### ISSUE THREAD

**Issue by adamveng** [medialab/hyphe#419]
When I create a new tag for a web entity cluster, and then press refresh or jump to another function in Hyphe, the tag is not saved. How do I save my tags?

**Comment by boogheta** [comment]
Hello,
Can you describe how you createed your tag exactly ? Please note that tags in Hyphe are categorized, meaning you need to input a category and a value. If you only created a category without inputting a value then if would not save anything.

**Comment by adamveng** [comment]
Ah, it was the value bit that I missed. Thanks!
