### ISSUE TITLE
Add a "latest prospects" feature in corpus

### ISSUE THREAD

**Issue by adamveng** [medialab/hyphe#420]
Don't know if its possible, but it would make it possible to see the prospects of one specific crawl.

**Comment by boogheta** [comment]
It is not presented as simply but you can do pretty much this already by going into the WebEntities list page, select only Discovered, Apply Changes, then click on "LAST MOD" to order by last modification time.

**Comment by adamveng** [comment]
Aha, great! This is really useful, thanks!

**Comment by boogheta** [comment]
closing this one, although we could try and make something like this along with #315
