### ISSUE TITLE
Exporting corpus to Gephi - no edges appear

### ISSUE THREAD

**Issue by adamveng** [medialab/hyphe#422]
Dear skilfull people

I am having troubles exporting my corpus to Gephi, as the edges between the nodes don't seem to be encoded in the .csv file exported from Hyphe. According to the Data Laboratory in Gephi there are no "source" and "target" data in the .csv file and therefore my corpus (which is a nicely interlinked network in Hyphe) appear as a lot of un-connected nodes in Gephi. Am I doing anything wrong in the export process?

Thanks in advance for reading - and for your great software!

Best,
Adam

**Comment by Yomguithereal** [comment]
Hello @adamveng. I thinks you would rather download a .gexf network file from the network tab of hyphe and load it in Gephi. It should save you the hassle of importing the csv file in Gephi which requires to relabel the file's columns beforehand if I remember correctly.

**Comment by adamveng** [comment]
Aha, amazing, thanks a lot, @Yomguithereal, this made my day!

**Comment by boogheta** [comment]
Thanks @Yomguithereal for your quick reaction.
This reminds me we should work quickly on #370
