### ISSUE TITLE
Can't log in to the corpus

### ISSUE THREAD

**Issue by Agnes-researcher** [medialab/hyphe#434]
Hey, Happy New Year. I've been having trouble logging into the interface. and I can't see the visual interface when I use hyphe browser.

**Comment by boogheta** [comment]
Hello @Agnes-researcher , I assume you're talking about the demo version of Hyphe ?
It seems it met some server outage which needs some fixing, I'll let you know when it's back up.

**Comment by boogheta** [comment]
Should be already good now!
