### ISSUE TITLE
Lien dans le wiki de Hyphe

### ISSUE THREAD

**Issue by heloisethero** [medialab/hyphe#436]
C'est juste un tout petit truc mineur...

Dans le [wiki de hyphe](https://github.com/medialab/hyphe/wiki), quand on clique sur le lien de:
"See also [these videos about Hyphe](https://www.youtube.com/channel/UCa630YAfmxMbdra20BIW0xA)"
On tombe sur une chaîne YT où il y a écrit "chaîne sans contenu", ce qui est un peu suprenant je trouve. 

Il vaudrait peut-être mieux mettre ce lien-ci qui redirige vers la liste des 6 vidéos de Mathieu sur Hyphe (très intéressantes par ailleurs):
https://www.youtube.com/watch?v=ZKc0fJ9gdlQ&list=PLQJhL9BD4W1QMaclCM99ijt2RVAEBIg9y

**Comment by boogheta** [comment]
Done! merci :)
