### ISSUE TITLE
Sélection multiple de web entities

### ISSUE THREAD

**Issue by g-arcas** [medialab/hyphe#443]
Est-il possible de sélectionner plusieurs discovered web entities dans le menu Prospect afin de les qualifier (IN ou OUT) en un clic, ce qui serait particulièrement pratiquer quand on remonte plusieurs milliers de web entities ?

**Comment by boogheta** [comment]
Pas directement depuis la page Prospect mais via la recherche dans la page webentities on peut faire cela oui.
En ne sélectionnant que les entités DISCOVERED et en cliquant sur Cited pour les trier depuis cette page on obtient la même liste que dans la page Prospect.
Attention cependant le cas échéant de ne pas oublier également de crawler les entités settées en IN par ce biais!
