### ISSUE TITLE
Configuration of desktop version in macOS (12.3)

### ISSUE THREAD

**Issue by Sofiatypa** [medialab/hyphe#451]
Hi folks,

first of all congrats on developing such a handy tool for social scientists! I am new in network analysis and, so far, online hyphe has been absolutely great and user friendly. 
I now got hooked and want to install the desktop version that will allow me to conduct 3-click analysis. And I have a question for beginners: How can I configure it?  I actually do not know where I should copy the default configuration files to (step 3 in [How to install?](https://github.com/medialab/hyphe)) and how to prepare the Docker containers (step 4). 

Could you please, please, please give me a hand with this? 

Thank you!

**Comment by boogheta** [comment]
Hello @Sofiatypa and sorry for the delay, did you figure out how to copy and edit the config files and start Docker? In short you need a basic understanding of the command line which you can run by searching in your Mac apps for "terminal". You should find tutorials for this online.

**Comment by Sofiatypa** [comment]
Hi Benjamin,

many thanks! I soon realised that this is more advanced than my knowledges permit and I asked for an IT professional’s help.
But thank you very much for reaching out! I watched your youtube videos too to learn hyphe, very comprehensive.

I am excited to use the ‘pro’ version, will let you know if I encounter any difficulties. And thumbs up for developing such a great tool for social scientists.

Cheers,

Sofia

Dr. Sofia Tipaldou
Research Fellow
PI, Wellcome ISSF, “Viro-populism”: how far-right populists spread fake-news on COVID-19 across Europe
School of Arts, Languages and Cultures (SALC)
The University of Manchester
Oxford Road
M13 9PL
webpage: http://goo.gl/jAvWC3

On 11 Apr 2022, at 12:46, Benjamin Ooghe-Tabanou ***@***.******@***.***>> wrote:



Hello @Sofiatypa<https://github.com/Sofiatypa> and sorry for the delay, did you figure out how to copy and edit the config files and start Docker? In short you need a basic understanding of the command line which you can run by searching in your Mac apps for "terminal". You should find tutorials for this online.
