### ISSUE TITLE
Add ability to remove a web entity

### ISSUE THREAD

**Issue by slauriere** [medialab/hyphe#472]
That'd be great to add the ability to remove a web entity (unless already available, but could not find it). Use case: it was added by mistake or it proves to be less interesting than hoped for once crawled.

**Comment by Yomguithereal** [comment]
Setting it as OUT does what you want, no? It won't drop its data from the database, of course, but it can be valuable to keep it sometimes. Or do you want to drop it for performance/storage reasons here?

**Comment by slauriere** [comment]
Thanks, works perfectly indeed 🙂. I thought at first sight that IN and OUT were more for incoming / outgoing edges but it makes sense like this and no need to drop the entity entirely in my case.
