### ISSUE TITLE
The demo version won't crawl in chrome?

### ISSUE THREAD

**Issue by Bseis** [medialab/hyphe#493]
The demo version/browser version wont crawl in chrome? It just say pending and nothing happens - any tips?

**Comment by boogheta** [comment]
Hello
This has no link whatsoever with the browser you're using as the crawls run on a server, not in your interface.
But there was indeed an issue with the server which I've just restarted, if you open your corpus again the pending crawls should now start

**Comment by Bseis** [comment]
i think there is once again a problem with the server
