### ISSUE TITLE
Pending for more URLS

### ISSUE THREAD

**Issue by SeyedAlirezaMalih** [medialab/hyphe#497]
I am trying to import more than 25 URLS to crawl, but the page pending after 25 URLS.

**Comment by Yomguithereal** [comment]
Without more information, I am afraid I cannot help you. Are you running an instance locally? What do you mean by pending?

**Comment by SeyedAlirezaMalih** [comment]
> Without more information, I am afraid I cannot help you. Are you running an instance locally? What do you mean by pending?

yes im trying to crawl more than 25 urls in my own server, but when try to insert more than 25 urls in /import urls or even tried to put a file which contains more than 25 urls in the import section, but the page trying to pending or loading, and never finished. 
I hope it would be clear :), tnx
