### ISSUE TITLE
Ubuntu install instructions

### ISSUE THREAD

**Issue by robhammond** [medialab/hyphe#64]
Have tried to install several times on different clean Ubuntu servers, none successfully.

I needed to run `sudo apt-get install maven`, `sudo apt-get install build-essential` which isn't covered in install instructions, in order to get the git clone working.

After that I get the web interface & lucene instance running ok, but get JSON errors on AJAX connections to localhost:6978 when trying to save any data, can't figure that one out.

**Comment by boogheta** [comment]
Hi @robhammond, FYI, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe now.
