### ISSUE TITLE
How to add a new prefix (alias) to Web entity ?

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#66]
We can merge a web entity into an existing one if they both belong to the same tree of LRU.

But how to merge a web entity to an existing one somewhere in the LRU tree ?

More precisely : how to add a new prefix to a web entity ?

Example : 
www.medialab.sciences-po.fr is a web entity.
I want to add as a prefix www.vimeo.com/medialab

How can I do that with the interface ?

**Comment by boogheta** [comment]
handled in new front
