### ISSUE TITLE
Hyphe installation under Fedora

### ISSUE THREAD

**Issue by RenePaul** [medialab/hyphe#71]
Dear all,

I am very new, so this is why I looking for your help.

Where could I find the method to install Hyphe under Fedora 20.
I found the script for installing it under Debian an Ubuntu, not Fedora.

Many thanks for your help.

**Comment by boogheta** [comment]
the soon to come release has been built in order to work on various distributions and different versions, please try it then.

**Comment by ElCep** [comment]
Sorry to reopen this  issue,
I'm on fedora 22 and I'm not able to finish properly the `./install.sh` with the last releases. Can you give me a hand ? 
E.

**Comment by boogheta** [comment]
@ElCep Happy to try and help, but you need to give me more information! ;)
For a better reactivity it might also be easier to chat on IRC, you can find me as Roux_taff on irc.freenode.net #medialab

**Comment by boogheta** [comment]
Hey @RenePaul, FYI, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe now.
