### ISSUE TITLE
install hyphe on window

### ISSUE THREAD

**Issue by mzuer** [medialab/hyphe#77]
Hi,

I'm not very skilled with this kind of programm and I'm not sure that I have understood how hyphe can be installed, but I have tried to install hyphe on my computer (windows 8) without success. Is it only possible to install hyphe with window ? What should I do after downloading the file "hyphe-v0.1.tar.gz" ?

Thank you and sorry if this question is too silly...

**Comment by boogheta** [comment]
Hey @mzuer, FYI, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe now on all OS, including Windows!
