### ISSUE TITLE
Iframe breaker breakers

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe#99]
After some tests, it appears that your best shot against JavaScript frame breakers is the HTML5 iframe `sandbox` attribute. Especially the `allow-top-navigation` rule. It totally beats `top === window` tricks.

This [article](http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/) is pretty useful concerning the issue.

The other tricky thing would then be the HTTP `X-Frame-Options` header. And for this I am afraid there won't be any other option than a browser extension overriding HTTP headers or a server query.

**Comment by boogheta** [comment]
handled via https://github.com/medialab/hyphe-browser
